cl = {
	"name": "Alesis",
	
    "leds": {
        "1": {
            "channel": 1,
            "midi": [176, 42, 0, 176],
            "actions": ["stop", ""],
            "toggle": 0,
            "track": 0,
        },
        "2": {
            "channel": 1,
            "midi": [176, 41, 0, 176],
            "actions": ["start", ""],
            "toggle": 0,
            "track": 0,
        },
        "3": {
            "channel": 1,
            "midi": [176, 45, 0, 176],
            "actions": ["record", ""],
            "toggle": 0,
            "track": 0,
        },
    },
    "jog_wheel": {},
    "defaults": {
        "octaves": 5,
        "sequence_length": 16,
        "seq_mult": 1,
        "plugin_control": 1,
        "mixer_tracks": 8,
        "Keyboard": 0,
        "Sequencer": 0,
        "keyboard_count": 5,
        "modes": [
            "Buttons",
            "Keyboard",
            "Sequencer",
        ],
        "levels_control_parameter": 1,
        "colors": [],
        "root": "C",
        "scale": "Major",
        "windows": [
            4,
            0,
            2,
            1,
            3,
        ],
    },

    "encoders": {
        "1": {
            "channel": 1,
            "midi": [176, 16, 75, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 1,
        },
        "2": {
            "channel": 1,
            "midi": [176, 17, 80, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 2,
        },
        "3": {
            "channel": 1,
            "midi": [176, 18, 47, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 3,
        },
        "4": {
            "channel": 1,
            "midi": [176, 19, 42, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 4,
        },
        "5": {
            "channel": 1,
            "midi": [176, 21, 88, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 5,
        },
        "6": {
            "channel": 1,
            "midi": [176, 21, 80, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 6,
        },
        "7": {
            "channel": 1,
            "midi": [176, 22, 74, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 7,
        },
        "8": {
            "channel": 1,
            "midi": [176, 23, 65, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 8,
        },
        "9": {
            "channel": 1,
            "midi": [176, 0, 87, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 1,
        },
        "10": {
            "channel": 1,
            "midi": [176, 1, 96, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 2,
        },
        "11": {
            "channel": 1,
            "midi": [176, 2, 86, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 3,
        },
        "12": {
            "channel": 1,
            "midi": [176, 3, 5, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 4,
        },
        "13": {
            "channel": 1,
            "midi": [176, 4, 4, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 5,
        },
        "14": {
            "channel": 1,
            "midi": [176, 5, 5, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 6,
        },
        "15": {
            "channel": 1,
            "midi": [176, 6, 14, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 7,
        },
        "16": {
            "channel": 1,
            "midi": [176, 7, 10, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 8,
        },
    },

    "buttons": {
        "17": {
            "channel": 1,
            "midi": [176, 58, 0, 176],
            "actions": ["rand_pattern", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "18": {
            "channel": 1,
            "midi": [176, 59, 0, 176],
            "actions": ["increment_scale", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "19": {
            "channel": 1,
            "midi": [176, 46, 0, 176],
            "actions": ["change_mode", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "20": {
            "channel": 1,
            "midi": [176, 60, 0, 176],
            "actions": ["rotate_set_windows", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "21": {
            "channel": 1,
            "midi": [176, 61, 0, 176],
            "actions": ["left", "shift"],
            "toggle": 0,
            "track": 0,
        },
        "22": {
            "channel": 1,
            "midi": [176, 62, 0, 176],
            "actions": ["right", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "23": {
            "channel": 1,
            "midi": [176, 43, 0, 176],
            "actions": ["previous", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "24": {
            "channel": 1,
            "midi": [176, 44, 0, 176],
            "actions": ["next", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "25": {
            "channel": 1,
            "midi": [176, 42, 0, 176],
            "actions": ["stop", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "26": {
            "channel": 1,
            "midi": [176, 41, 0, 176],
            "actions": ["start", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "27": {
            "channel": 1,
            "midi": [176, 45, 0, 176],
            "actions": ["trig_clip", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "33": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "34": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 2,
        },
        "35": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 3,
        },
        "36": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 4,
        },
        "37": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 5,
        },
        "38": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 6,
        },
        "39": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 7,
        },
        "40": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 8,
        },
        "41": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "42": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 2,
        },
        "43": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 3,
        },
        "44": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 4,
        },
        "45": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 5,
        },
        "46": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 6,
        },
        "47": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 7,
        },
        "48": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 8,
        },
        "49": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "50": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 2,
        },
        "51": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 3,
        },
        "52": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 4,
        },
        "53": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 5,
        },
        "54": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 6,
        },
        "55": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 7,
        },
        "56": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 8,
        },
    },
    
    "performance": {
        "1": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 0,
        },
        "2": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 1,
        },
        "3": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 2,
        },
        "4": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 3,
        },
        "5": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 0,
        },
        "6": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 1,
        },
        "7": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 2,
        },
        "8": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 3,
        },
        "9": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 0,
        },
        "10": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 1,
        },
        "11": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 2,
        },
        "12": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 3,
        },
        "13": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 0,
        },
        "14": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 1,
        },
        "15": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 2,
        },
        "16": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 3,
        },
        "17": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 0,
        },
        "18": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 1,
        },
        "19": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 2,
        },
        "20": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 3,
        },
        "21": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 0,
        },
        "22": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 1,
        },
        "23": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 2,
        },
        "24": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 3,
        },
    },
    "keyboard": {
        "1": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["C#", ""],
            "toggle": 0,
            "track": 0,
        },
        "2": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["D#", ""],
            "toggle": 0,
            "track": 0,
        },
        "3": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["F#", ""],
            "toggle": 0,
            "track": 0,
        },
        "4": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["G#", ""],
            "toggle": 0,
            "track": 0,
        },
        "5": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["A#", ""],
            "toggle": 0,
            "track": 0,
        },
        "6": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["C", ""],
            "toggle": 0,
            "track": 0,
        },
        "7": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["D", ""],
            "toggle": 0,
            "track": 0,
        },
        "8": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["E", ""],
            "toggle": 0,
            "track": 0,
        },
        "9": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["F", ""],
            "toggle": 0,
            "track": 0,
        },
        "10": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["G", ""],
            "toggle": 0,
            "track": 0,
        },
        "11": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["A", ""],
            "toggle": 0,
            "track": 0,
        },
        "12": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["B", ""],
            "toggle": 0,
            "track": 0,
        },
        "13": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["C#", ""],
            "toggle": 0,
            "track": 1,
        },
        "14": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["D#", ""],
            "toggle": 0,
            "track": 1,
        },
        "15": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["F#", ""],
            "toggle": 0,
            "track": 1,
        },
        "16": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["G#", ""],
            "toggle": 0,
            "track": 1,
        },
        "17": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["A#", ""],
            "toggle": 0,
            "track": 1,
        },
        "18": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["C", ""],
            "toggle": 0,
            "track": 1,
        },
        "19": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["D", ""],
            "toggle": 0,
            "track": 1,
        },
        "20": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["E", ""],
            "toggle": 0,
            "track": 1,
        },
        "21": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["F", ""],
            "toggle": 0,
            "track": 1,
        },
        "22": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["G", ""],
            "toggle": 0,
            "track": 1,
        },
        "23": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["A", ""],
            "toggle": 0,
            "track": 1,
        },
        "24": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["B", ""],
            "toggle": 0,
            "track": 1,
        },
    },
    "sequencer": {
        "1": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["0", "0"],
            "toggle": 0,
            "track": 0,
        },
        "2": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["1", "1"],
            "toggle": 0,
            "track": 0,
        },
        "3": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["2", "2"],
            "toggle": 0,
            "track": 0,
        },
        "4": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["3", "3"],
            "toggle": 0,
            "track": 0,
        },
        "5": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["4", "4"],
            "toggle": 0,
            "track": 0,
        },
        "6": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["5", "5"],
            "toggle": 0,
            "track": 0,
        },
        "7": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["6", "6"],
            "toggle": 0,
            "track": 0,
        },
        "8": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["7", "7"],
            "toggle": 0,
            "track": 0,
        },
        "9": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["8", "8"],
            "toggle": 0,
            "track": 0,
        },
        "10": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["9", "9"],
            "toggle": 0,
            "track": 0,
        },
        "11": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["10", "10"],
            "toggle": 0,
            "track": 0,
        },
        "12": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["11", "11"],
            "toggle": 0,
            "track": 0,
        },
        "13": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["12", "12"],
            "toggle": 0,
            "track": 0,
        },
        "14": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["13", "13"],
            "toggle": 0,
            "track": 0,
        },
        "15": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["14", "14"],
            "toggle": 0,
            "track": 0,
        },
        "16": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["15", "15"],
            "toggle": 0,
            "track": 0,
        },
        "17": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["16", "16"],
            "toggle": 0,
            "track": 1,
        },
        "18": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["17", "17"],
            "toggle": 0,
            "track": 1,
        },
        "19": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["18", "18"],
            "toggle": 0,
            "track": 1,
        },
        "20": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["19", "19"],
            "toggle": 0,
            "track": 1,
        },
        "21": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["20", "20"],
            "toggle": 0,
            "track": 1,
        },
        "22": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["21", "21"],
            "toggle": 0,
            "track": 1,
        },
        "23": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["22", "22"],
            "toggle": 0,
            "track": 1,
        },
        "24": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["23", "23"],
            "toggle": 0,
            "track": 1,
        },
    },
}

