# cl = {
#     "jog_wheel": {
#         "86": {
#             "channel": 1,
#             "midi": [
#                 176,
#                 60,
#                 1,
#                 176
#             ],
#             "actions": ["jog_wheel_up", ""],
#             "toggle": 0,
#             "track": 1
#         },
#         "87": {
#             "channel": 1,
#             "midi": [
#                 176,
#                 60,
#                 65,
#                 176  # add
#             ],
#             "actions": ["jog_wheel_down", ""],
#             "toggle": 0,
#             "track": 1
#         },
#     },

#     "defaults": { 
#         "octaves": 5, 
#         "plugin_control": 1, 
#         "mixer_tracks": 8, 
#         "Keyboard": 0, 
#         "Sequencer": 0, 
#         "keyboard_count": 5, 
#         "modes": ["Buttons", "Keyboard", "Sequencer", ], 
#         "levels_control_parameter": 1, 
#         "colors": [], 
#         "root": "C", 
#         "scale": "Major", 
#         "windows": [4, 0, 2, 1, 3, ] 
#     },

#     # "defaults": { 
#     #     "plugin_control": 1,
#     #     "octaves": 5, 
#     #     "sequence_multiple": [0, 32], 
#     #     "Keyboard": 0, 
#     #     "Sequencer": 0, 
#     #     "keyboard_count": 5, 
#     #     "modes": ["Buttons", "Keyboard", "Sequencer", ], 
#     #     "levels_control_parameter": 1, "colors": [], 
#     #      "root": "C",  
#     #      "scale": "Major", 
#     #      "windows": [4, 0, 2, 1, 3, ] },

#     "encoders": {
#         "1": {
#             "channel": 1,
#             "midi": [176, 0, 57, 176],
#             "actions": ["mixer_level", "mixer_pan(001)"],
#             "toggle": 0,
#             "track": 1,
#         },
#         "2": {
#             "channel": 1,
#             "midi": [176, 1, 107, 176],
#             "actions": ["mixer_level", "mixer_pan(001)"],
#             "toggle": 0,
#             "track": 2,
#         },
#         "3": {
#             "channel": 1,
#             "midi": [176, 2, 56, 176],
#             "actions": ["mixer_level", "mixer_level(002)"],
#             "toggle": 0,
#             "track": 3,
#         },
#         "4": {
#             "channel": 1,
#             "midi": [176, 17, 65, 176],
#             "actions": ["set_random_max_octave", "mixer_level(003)"],
#             "toggle": 0,
#             "track": 3,
#         },
#         "14": {
#             "channel": 1,
#             "midi": [176, 17, 65, 176],
#             "actions": ["set_random_max_octave", "mixer_level(003)"],
#             "toggle": 0,
#             "track": 1,
#         },        
#         "5": {
#             "channel": 1,
#             "midi": [176, 18, 19, 176],
#             "actions": ["selected_level", "mixer_level(004)"],
#             "toggle": 0,
#             "track": 1,
#         },
#         "6": {
#             "channel": 1,
#             "midi": [176, 19, 82, 176],
#             "actions": ["selected_pan", "mixer_level(005)"],
#             "toggle": 0,
#             "track": 1,
#         },
#         "7": {
#             "channel": 1,
#             "midi": [176, 20, 83, 176],
#             "actions": ["set_random_offset", "mixer_level(006)"],
#             "toggle": 0,
#             "track": 1,
#         },
#         "8": {
#             "channel": 1,
#             "midi": [176, 21, 64, 176],
#             "actions": ["set_random_min_octave", "mixer_level(007)"],
#             "toggle": 0,
#             "track": 1,
#         },
#         "8": {
#             "channel": 1,
#             "midi": [176, 16, 64, 176],
#             "actions": ["mixer_pan", "mixer_level(007)"],
#             "toggle": 0,
#             "track": 1,
#         },
#     },

#     # "buttons": {
#     #     "9": {
#     #         "channel": 1,
#     #         "midi": [176, 24, 0, 176],
#     #         "actions": ["change_step_parameter", "copy"],
#     #         "toggle": 0,
#     #     },
#     #     "10": {
#     #         "channel": 1,
#     #         "midi": [176, 25, 0, 176],
#     #         "actions": ["change_mode", "paste"],
#     #         "toggle": 0,
#     #     },
#     #     "11": {
#     #         "channel": 1,
#     #         "midi": [176, 26, 0, 176],
#     #         "actions": ["up", "rand_pat"],
#     #         "toggle": 0,
#     #     },
#     #     "12": {
#     #         "channel": 1,
#     #         "midi": [176, 27, 0, 176],
#     #         "actions": ["enter", "rand_notes"],
#     #         "toggle": 0,
#     #     },
#     #     "13": {
#     #         "channel": 1,
#     #         "midi": [176, 28, 0, 176],
#     #         "actions": ["shift", "shift"],
#     #         "toggle": 0,
#     #     },
#     #     "14": {
#     #         "channel": 1,
#     #         "midi": [176, 29, 0, 176],
#     #         "actions": ["left", "nothing"],
#     #         "toggle": 0,
#     #     },
#     #     "15": {
#     #         "channel": 1,
#     #         "midi": [176, 30, 0, 176],
#     #         "actions": ["down", "set_root_note"],
#     #         "toggle": 0,
#     #     },
#     #     "16": {
#     #         "channel": 1,
#     #         "midi": [176, 31, 0, 176],
#     #         "actions": ["right", "set_step_range"],
#     #         "toggle": 0,
#     #     },
#     #     "90": {
#     #         "channel": 1,
#     #         "midi": [144, 36, 0, 176],
#     #         "actions": ["up", "set_step_range"],
#     #         "toggle": 0,
#     #     },
#     # },


#     "buttons": {
#         "1": {
#             "channel": 1,
#             "midi": [176, 48, 4, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 1,
#         },
#         "2": {
#             "channel": 1,
#             "midi": [176, 49, 4, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 2,
#         },
#         "3": {
#             "channel": 1,
#             "midi": [176, 50, 0, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 3,
#         },
#         "4": {
#             "channel": 1,
#             "midi": [176, 51, 0, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 4,
#         },
#         "5": {
#             "channel": 1,
#             "midi": [176, 52, 0, 176],
#             "actions": ["mixer_mute", "solo"],
#             # "actions": ["mute", "solo"],
#             # "actions": ["mixer_mute", "solo"],
#             # "actions": ["mixer_mute", "solo"],
#             # "actions": ["mixer_mute", "solo"],
#             # "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 5,
#         },
#         "6": {
#             "channel": 1,
#             "midi": [176, 53, 0, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 6,
#         },
#         "7": {
#             "channel": 1,
#             "midi": [176, 54, 0, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 7,
#         },
#         "8": {
#             "channel": 1,
#             "midi": [176, 55, 0, 176],
#             "actions": ["mixer_mute", "solo"],
#             "toggle": 0,
#             "track": 8,
#         },
#     },
#     "keyboard": {
#         "50": {
#             "channel": 10,
#             "midi": [144, 52, 0, 128],
#             "actions": ["C#0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "51": {
#             "channel": 10,
#             "midi": [144, 53, 0, 128],
#             "actions": ["D#0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "52": {
#             "channel": 10,
#             "midi": [144, 55, 0, 128],
#             "actions": ["F#0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "53": {
#             "channel": 10,
#             "midi": [144, 56, 0, 128],
#             "actions": ["G#0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "54": {
#             "channel": 10,
#             "midi": [144, 57, 0, 128],
#             "actions": ["A#0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "55": {
#             "channel": 10,
#             "midi": [144, 36, 0, 128],
#             "actions": ["C0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "56": {
#             "channel": 10,
#             "midi": [144, 37, 0, 128],
#             "actions": ["D0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "57": {
#             "channel": 10,
#             "midi": [144, 38, 0, 128],
#             "actions": ["E0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "58": {
#             "channel": 10,
#             "midi": [144, 39, 0, 128],
#             "actions": ["F0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "59": {
#             "channel": 10,
#             "midi": [144, 40, 0, 128],
#             "actions": ["G0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "60": {
#             "channel": 10,
#             "midi": [144, 41, 0, 128],
#             "actions": ["A0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "61": {
#             "channel": 10,
#             "midi": [144, 42, 0, 128],
#             "actions": ["B0", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "62": {
#             "channel": 10,
#             "midi": [144, 59, 0, 128],
#             "actions": ["C#1", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "63": {
#             "channel": 10,
#             "midi": [144, 60, 0, 128],
#             "actions": ["D#1", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "64": {
#             "channel": 10,
#             "midi": [144, 62, 0, 128],
#             "actions": ["F#1", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         "65": {
#             "channel": 10,
#             "midi": [144, 63, 0, 128],
#             "actions": ["G#1", ""],
#             "toggle": 0,
#             "track": 1,
#         },
#         # "66": {
#         #     "channel": 10,
#         #     "midi": [144, 64, 0, 128],
#         #     "actions": ["A#1", ""],
#         #     "toggle": 0,
#         # },
#         # "67": {
#         #     "channel": 10,
#         #     "midi": [144, 43, 0, 128],
#         #     "actions": ["C1", ""],
#         #     "toggle": 0,
#         # },
#         # "68": {
#         #     "channel": 10,
#         #     "midi": [144, 44, 0, 128],
#         #     "actions": ["D1", ""],
#         #     "toggle": 0,
#         # },
#         # "69": {
#         #     "channel": 10,
#         #     "midi": [144, 45, 0, 128],
#         #     "actions": ["E1", ""],
#         #     "toggle": 0,
#         # },
#         # "70": {
#         #     "channel": 10,
#         #     "midi": [144, 46, 0, 128],
#         #     "actions": ["F1", ""],
#         #     "toggle": 0,
#         # },
#         # "71": {
#         #     "channel": 10,
#         #     "midi": [144, 47, 0, 128],
#         #     "actions": ["G1", ""],
#         #     "toggle": 0,
#         # },
#         # "72": {
#         #     "channel": 10,
#         #     "midi": [144, 48, 0, 128],
#         #     "actions": ["A1", ""],
#         #     "toggle": 0,
#         # },
#         # "73": {
#         #     "channel": 10,
#         #     "midi": [144, 49, 0, 128],
#         #     "actions": ["B1", ""],
#         #     "toggle": 0,
#         # },
#         # "74": {
#         #     "channel": 10,
#         #     "midi": [144, 66, 0, 128],
#         #     "actions": ["C#2", ""],
#         #     "toggle": 0,
#         # },
#         # "75": {
#         #     "channel": 10,
#         #     "midi": [144, 67, 0, 128],
#         #     "actions": ["D#2", ""],
#         #     "toggle": 0,
#         # },
#         # "79": {
#         #     "channel": 10,
#         #     "midi": [144, 50, 0, 128],
#         #     "actions": ["C2", ""],
#         #     "toggle": 0,
#         # },
#         # "80": {
#         #     "channel": 10,
#         #     "midi": [144, 51, 0, 128],
#         #     "actions": ["D2", ""],
#         #     "toggle": 0,
#         # },
#     },

#     "sequencer": {
#         "18": {
#             "channel": 10,
#             "midi": [144, 52, 0, 128],
#             "actions": ["0", "0"],
#             "toggle": 0,
#             "track": 1,
#         },
#         # "19": {
#         #     "channel": 10,
#         #     "midi": [144, 53, 0, 128],
#         #     "actions": ["1", "1"],
#         #     "toggle": 0,
#         # },
#         # "20": {
#         #     "channel": 10,
#         #     "midi": [144, 54, 0, 128],
#         #     "actions": ["2", "2"],
#         #     "toggle": 0,
#         # },
#         # "21": {
#         #     "channel": 10,
#         #     "midi": [144, 55, 0, 128],
#         #     "actions": ["3", "3"],
#         #     "toggle": 0,
#         # },
#         # "22": {
#         #     "channel": 10,
#         #     "midi": [144, 56, 0, 128],
#         #     "actions": ["4", "4"],
#         #     "toggle": 0,
#         # },
#         # "23": {
#         #     "channel": 10,
#         #     "midi": [144, 57, 0, 128],
#         #     "actions": ["5", "5"],
#         #     "toggle": 0,
#         # },
#         # "24": {
#         #     "channel": 10,
#         #     "midi": [144, 58, 0, 128],
#         #     "actions": ["6", "6"],
#         #     "toggle": 0,
#         # },
#         # "25": {
#         #     "channel": 10,
#         #     "midi": [144, 59, 0, 128],
#         #     "actions": ["7", "7"],
#         #     "toggle": 0,
#         # },
#         # "26": {
#         #     "channel": 10,
#         #     "midi": [144, 60, 0, 128],
#         #     "actions": ["8", "8"],
#         #     "toggle": 0,
#         # },
#         # "27": {
#         #     "channel": 10,
#         #     "midi": [144, 61, 0, 128],
#         #     "actions": ["9", "9"],
#         #     "toggle": 0,
#         # },
#         # "28": {
#         #     "channel": 10,
#         #     "midi": [144, 62, 0, 128],
#         #     "actions": ["10", "10"],
#         #     "toggle": 0,
#         # },
#         # "29": {
#         #     "channel": 10,
#         #     "midi": [144, 63, 0, 128],
#         #     "actions": ["11", "11"],
#         #     "toggle": 0,
#         # },
#         # "30": {
#         #     "channel": 10,
#         #     "midi": [144, 64, 0, 128],
#         #     "actions": ["12", "12"],
#         #     "toggle": 0,
#         # },
#         # "31": {
#         #     "channel": 10,
#         #     "midi": [144, 65, 0, 128],
#         #     "actions": ["13", "13"],
#         #     "toggle": 0,
#         # },
#         # "32": {
#         #     "channel": 10,
#         #     "midi": [144, 66, 0, 128],
#         #     "actions": ["14", "14"],
#         #     "toggle": 0,
#         # },
#         # "33": {
#         #     "channel": 10,
#         #     "midi": [144, 67, 0, 128],
#         #     "actions": ["15", "15"],
#         #     "toggle": 0,
#         # },
#         # "34": {
#         #     "channel": 10,
#         #     "midi": [144, 36, 0, 128],
#         #     "actions": ["16", "16"],
#         #     "toggle": 0,
#         # },
#         # "35": {
#         #     "channel": 10,
#         #     "midi": [144, 37, 0, 128],
#         #     "actions": ["17", "17"],
#         #     "toggle": 0,
#         # },
#         # "36": {
#         #     "channel": 10,
#         #     "midi": [144, 38, 0, 128],
#         #     "actions": ["18", "18"],
#         #     "toggle": 0,
#         # },
#         # "37": {
#         #     "channel": 10,
#         #     "midi": [144, 39, 0, 128],
#         #     "actions": ["19", "19"],
#         #     "toggle": 0,
#         # },
#         # "38": {
#         #     "channel": 10,
#         #     "midi": [144, 40, 0, 128],
#         #     "actions": ["20", "20"],
#         #     "toggle": 0,
#         # },
#         # "39": {
#         #     "channel": 10,
#         #     "midi": [144, 41, 0, 128],
#         #     "actions": ["21", "21"],
#         #     "toggle": 0,
#         # },
#         # "40": {
#         #     "channel": 10,
#         #     "midi": [144, 42, 0, 128],
#         #     "actions": ["22", "22"],
#         #     "toggle": 0,
#         # },
#         # "41": {
#         #     "channel": 10,
#         #     "midi": [144, 43, 0, 128],
#         #     "actions": ["23", "23"],
#         #     "toggle": 0,
#         # },
#         # "42": {
#         #     "channel": 10,
#         #     "midi": [144, 44, 0, 128],
#         #     "actions": ["24", "24"],
#         #     "toggle": 0,
#         # },
#         # "43": {
#         #     "channel": 10,
#         #     "midi": [144, 45, 0, 128],
#         #     "actions": ["25", "25"],
#         #     "toggle": 0,
#         # },
#         # "44": {
#         #     "channel": 10,
#         #     "midi": [144, 46, 0, 128],
#         #     "actions": ["26", "26"],
#         #     "toggle": 0,
#         # },
#         # "45": {
#         #     "channel": 10,
#         #     "midi": [144, 47, 0, 128],
#         #     "actions": ["27", "27"],
#         #     "toggle": 0,
#         # },
#         # "46": {
#         #     "channel": 10,
#         #     "midi": [144, 48, 0, 128],
#         #     "actions": ["28", "28"],
#         #     "toggle": 0,
#         # },
#         # "47": {
#         #     "channel": 10,
#         #     "midi": [144, 49, 0, 128],
#         #     "actions": ["29", "29"],
#         #     "toggle": 0,
#         # },
#         # "48": {
#         #     "channel": 10,
#         #     "midi": [144, 50, 0, 128],
#         #     "actions": ["30", "30"],
#         #     "toggle": 0,
#         # },
#         # "49": {
#         #     "channel": 10,
#         #     "midi": [144, 51, 0, 128],
#         #     "actions": ["31", "31"],
#         #     "toggle": 0,
#         # },
#     },
# }

cl = {
    "jog_wheel": {},



    "defaults": { "octaves": 5, "sequence_length": 16, "seq_mult": 1, "plugin_control": 1, "mixer_tracks": 1, "Keyboard": 0, "Sequencer": 0, "keyboard_count": 5, "modes": ["Buttons", "Keyboard", "Sequencer", ], "levels_control_parameter": 1, "colors": [], "root": "C", "scale": "Major", "windows": [4, 0, 2, 1, 3, ] },

    "encoders": {
        "1": {
            "channel": 1,
            "midi": [176, 16, 75, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 1,
        },
        "2": {
            "channel": 1,
            "midi": [176, 17, 80, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 2,
        },
        "3": {
            "channel": 1,
            "midi": [176, 18, 47, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 3,
        },
        "4": {
            "channel": 1,
            "midi": [176, 19, 42, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 4,
        },
        "5": {
            "channel": 1,
            "midi": [176, 21, 88, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 5,
        },
        "6": {
            "channel": 1,
            "midi": [176, 21, 80, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 6,
        },
        "7": {
            "channel": 1,
            "midi": [176, 22, 74, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 7,
        },
        "8": {
            "channel": 1,
            "midi": [176, 23, 65, 176],
            "actions": ["mixer_pan", "selected_level"],
            "toggle": 0,
            "track": 8,
        },
        "9": {
            "channel": 1,
            "midi": [176, 0, 87, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 1,
        },
        "10": {
            "channel": 1,
            "midi": [176, 1, 96, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 2,
        },
        "11": {
            "channel": 1,
            "midi": [176, 2, 86, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 3,
        },
        "12": {
            "channel": 1,
            "midi": [176, 3, 5, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 4,
        },
        "13": {
            "channel": 1,
            "midi": [176, 4, 4, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 5,
        },
        "14": {
            "channel": 1,
            "midi": [176, 5, 5, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 6,
        },
        "15": {
            "channel": 1,
            "midi": [176, 6, 14, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 7,
        },
        "16": {
            "channel": 1,
            "midi": [176, 7, 10, 176],
            "actions": ["mixer_level", "selected_level"],
            "toggle": 0,
            "track": 8,
        },
    },

    "buttons": {
        "17": {
            "channel": 1,
            "midi": [176, 58, 0, 176],
            "actions": ["octave_up", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "18": {
            "channel": 1,
            "midi": [176, 59, 0, 176],
            "actions": ["octave_up", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "19": {
            "channel": 1,
            "midi": [176, 46, 0, 176],
            "actions": ["change_mode", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "20": {
            "channel": 1,
            "midi": [176, 60, 0, 176],
            "actions": ["rotate_set_windows", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "21": {
            "channel": 1,
            "midi": [176, 61, 0, 176],
            "actions": ["left", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "22": {
            "channel": 1,
            "midi": [176, 62, 0, 176],
            "actions": ["right", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "23": {
            "channel": 1,
            "midi": [176, 43, 0, 176],
            "actions": ["previous", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "24": {
            "channel": 1,
            "midi": [176, 44, 0, 176],
            "actions": ["next", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "25": {
            "channel": 1,
            "midi": [176, 42, 0, 176],
            "actions": ["stop", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "26": {
            "channel": 1,
            "midi": [176, 41, 0, 176],
            "actions": ["start", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "27": {
            "channel": 1,
            "midi": [176, 45, 0, 176],
            "actions": ["record", "solo"],
            "toggle": 0,
            "track": 0,
        },
        "33": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "34": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 2,
        },
        "35": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 3,
        },
        "36": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 4,
        },
        "37": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 5,
        },
        "38": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 6,
        },
        "39": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 7,
        },
        "40": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["mixer_solo", "solo"],
            "toggle": 0,
            "track": 8,
        },
        "41": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "42": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 2,
        },
        "43": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 3,
        },
        "44": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 4,
        },
        "45": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 5,
        },
        "46": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 6,
        },
        "47": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 7,
        },
        "48": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["mixer_mute", "solo"],
            "toggle": 0,
            "track": 8,
        },
        "49": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 1,
        },
        "50": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 2,
        },
        "51": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 3,
        },
        "52": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 4,
        },
        "53": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 5,
        },
        "54": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 6,
        },
        "55": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 7,
        },
        "56": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["mixer_record", "solo"],
            "toggle": 0,
            "track": 8,
        },
    },
    # "keyboard": {
    #     "73": {
    #         "channel": 1,
    #         "midi": [176, 49, 0, 176],
    #         "actions": ["C#0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "74": {
    #         "channel": 1,
    #         "midi": [176, 51, 0, 176],
    #         "actions": ["D#0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "75": {
    #         "channel": 1,
    #         "midi": [176, 54, 0, 176],
    #         "actions": ["F#0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "76": {
    #         "channel": 1,
    #         "midi": [176, 64, 0, 176],
    #         "actions": ["G#0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "77": {
    #         "channel": 1,
    #         "midi": [176, 66, 0, 176],
    #         "actions": ["A#0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "78": {
    #         "channel": 1,
    #         "midi": [176, 48, 0, 176],
    #         "actions": ["C0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "79": {
    #         "channel": 1,
    #         "midi": [176, 50, 0, 176],
    #         "actions": ["D0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "80": {
    #         "channel": 1,
    #         "midi": [176, 52, 0, 176],
    #         "actions": ["E0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "81": {
    #         "channel": 1,
    #         "midi": [176, 53, 0, 176],
    #         "actions": ["F0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "82": {
    #         "channel": 1,
    #         "midi": [176, 55, 0, 176],
    #         "actions": ["G0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "83": {
    #         "channel": 1,
    #         "midi": [176, 65, 0, 176],
    #         "actions": ["A0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "84": {
    #         "channel": 1,
    #         "midi": [176, 67, 0, 176],
    #         "actions": ["B0", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "85": {
    #         "channel": 1,
    #         "midi": [176, 69, 0, 176],
    #         "actions": ["C#1", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "86": {
    #         "channel": 1,
    #         "midi": [176, 71, 0, 176],
    #         "actions": ["D#1", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "90": {
    #         "channel": 1,
    #         "midi": [176, 68, 0, 176],
    #         "actions": ["C1", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "91": {
    #         "channel": 1,
    #         "midi": [176, 70, 0, 176],
    #         "actions": ["D1", ""],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    # },

    "keyboard": { 
            '1':     
                {'channel': 1, 
                'midi': [176, 33, 0, 176], 
                'actions': ['C#', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '2':
                {'channel': 1, 
                'midi': [176, 35, 0, 176], 
                'actions': ['D#', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '3':
                {'channel': 1, 
                'midi': [176, 38, 0, 176], 
                'actions': ['F#', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '4':
                {'channel': 1, 
                'midi': [176, 48, 0, 176], 
                'actions': ['G#', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '5':
                {'channel': 1, 
                'midi': [176, 50, 0, 176], 
                'actions': ['A#', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '6':
                {'channel': 1, 
                'midi': [176, 32, 0, 176], 
                'actions': ['C', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '7':
                {'channel': 1, 
                'midi': [176, 34, 0, 176], 
                'actions': ['D', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '8':
                {'channel': 1, 
                'midi': [176, 36, 0, 176], 
                'actions': ['E', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '9':
                {'channel': 1, 
                'midi': [176, 37, 0, 176], 
                'actions': ['F', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '10':
                {'channel': 1, 
                'midi': [176, 39, 0, 176], 
                'actions': ['G', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '11':
                {'channel': 1, 
                'midi': [176, 49, 0, 176], 
                'actions': ['A', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '12':
                {'channel': 1, 
                'midi': [176, 51, 0, 176], 
                'actions': ['B', ''], 
                'toggle': 0, 
                'track': 0 }, 
            '13':
                {'channel': 1, 
                'midi': [176, 53, 0, 176], 
                'actions': ['C#', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '14':
                {'channel': 1, 
                'midi': [176, 55, 0, 176], 
                'actions': ['D#', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '15':
                {'channel': 1, 
                'midi': [176, 66, 0, 176], 
                'actions': ['F#', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '16':
                {'channel': 1, 
                'midi': [176, 68, 0, 176], 
                'actions': ['G#', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '17':
                {'channel': 1, 
                'midi': [176, 70, 0, 176], 
                'actions': ['A#', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '18':
                {'channel': 1, 
                'midi': [176, 52, 0, 176], 
                'actions': ['C', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '19':
                {'channel': 1, 
                'midi': [176, 54, 0, 176], 
                'actions': ['D', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '20':
                {'channel': 1, 
                'midi': [176, 64, 0, 176], 
                'actions': ['E', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '21':
                {'channel': 1, 
                'midi': [176, 65, 0, 176], 
                'actions': ['F', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '22':
                {'channel': 1, 
                'midi': [176, 67, 0, 176], 
                'actions': ['G', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '23':
                {'channel': 1, 
                'midi': [176, 69, 0, 176], 
                'actions': ['A', ''], 
                'toggle': 0, 
                'track': 1 }, 
            '24':
                {'channel': 1, 
                'midi': [176, 71, 0, 176], 
                'actions': ['B', ''], 
                'toggle': 0, 
                'track': 1 },
            },  
    "sequencer": { 
        '1': {
            'channel': 1, 
            'midi': [176, 32, 0, 176], 
            'actions': ['0', '0'], 
            'toggle': 0, 
            'track': 0 }, 
        '2': {
            'channel': 1, 
            'midi': [176, 33, 0, 176], 
            'actions': ['1', '1'], 
            'toggle': 0, 
            'track': 0 }, 
        '3': {
            'channel': 1, 
            'midi': [176, 34, 0, 176], 
            'actions': ['2', '2'], 
            'toggle': 0, 
            'track': 0 }, 
        '4': {
            'channel': 1, 
            'midi': [176, 35, 0, 176], 
            'actions': ['3', '3'], 
            'toggle': 0, 
            'track': 0 }, 
        '5': {
            'channel': 1, 
            'midi': [176, 36, 0, 176], 
            'actions': ['4', '4'], 
            'toggle': 0, 
            'track': 0 }, 
        '6': {
            'channel': 1, 
            'midi': [176, 37, 0, 176], 
            'actions': ['5', '5'], 
            'toggle': 0, 
            'track': 0 }, 
        '7': {
            'channel': 1, 
            'midi': [176, 38, 0, 176], 
            'actions': ['6', '6'], 
            'toggle': 0, 
            'track': 0 }, 
        '8': {
            'channel': 1, 
            'midi': [176, 39, 0, 176], 
            'actions': ['7', '7'], 
            'toggle': 0, 
            'track': 0 }, 
        '9': {
            'channel': 1, 
            'midi': [176, 48, 0, 176], 
            'actions': ['8', '8'], 
            'toggle': 0, 
            'track': 0 }, 
        '10': {
            'channel': 1, 
            'midi': [176, 49, 0, 176], 
            'actions': ['9', '9'], 
            'toggle': 0, 
            'track': 0 }, 
        '11': {
            'channel': 1, 
            'midi': [176, 50, 0, 176], 
            'actions': ['10', '10'], 
            'toggle': 0, 
            'track': 0 }, 
        '12': {
            'channel': 1, 
            'midi': [176, 51, 0, 176], 
            'actions': ['11', '11'], 
            'toggle': 0, 
            'track': 0 }, 
        '13': {
            'channel': 1, 
            'midi': [176, 52, 0, 176], 
            'actions': ['12', '12'], 
            'toggle': 0, 
            'track': 0 }, 
        '14': {
            'channel': 1, 
            'midi': [176, 53, 0, 176], 
            'actions': ['13', '13'], 
            'toggle': 0, 
            'track': 0 }, 
        '15': {
            'channel': 1, 
            'midi': [176, 54, 0, 176], 
            'actions': ['14', '14'], 
            'toggle': 0, 
            'track': 0 }, 
        '16': {
            'channel': 1, 
            'midi': [176, 55, 0, 176], 
            'actions': ['15', '15'], 
            'toggle':0, 
            'track': 0 }, 
        '17': {
            'channel': 1, 
            'midi': [176, 64, 0, 176], 
            'actions': ['16', '16'], 
            'toggle': 0, 
            'track': 1 }, 
        '18': {
            'channel': 1, 
            'midi': [176, 65, 0, 176], 
            'actions': ['17', '17'], 
            'toggle': 0, 
            'track': 1}, 
        '19': {
            'channel': 1, 
            'midi': [176, 66, 0, 176], 
            'actions': ['18', '18'], 
            'toggle': 0, 
            'track': 1 }, 
        '20': {
            'channel': 1, 
            'midi': [176, 67, 0, 176], 
            'actions': ['19', '19'], 
            'toggle': 0, 
            'track': 1 }, 
        '21': {
            'channel': 1, 
            'midi': [176, 68, 0, 176], 
            'actions': ['20', '20'], 
            'toggle': 0, 
            'track': 1 }, 
        '22': {
            'channel': 1, 
            'midi': [176, 69, 0, 176], 
            'actions': ['21', '21'], 
            'toggle': 0, 
            'track': 1 }, 
        '23': {
            'channel': 1, 
            'midi': [176, 70, 0, 176], 
            'actions': ['22', '22'], 
            'toggle': 0, 
            'track': 1 }, 
        '24': {
            'channel': 1, 
            'midi': [176, 71, 0, 176], 
            'actions': ['23', '23'], 
            'toggle': 0, 
            'track': 1 }, },

    # "seque    ncer": {
    #     "57": {
    #         "channel": 1,
    #         "midi": [176, 48, 0, 176],
    #         "actions": ["0", "0"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "58": {
    #         "channel": 1,
    #         "midi": [176, 49, 0, 176],
    #         "actions": ["1", "1"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "59": {
    #         "channel": 1,
    #         "midi": [176, 50, 0, 176],
    #         "actions": ["2", "2"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "60": {
    #         "channel": 1,
    #         "midi": [176, 51, 0, 176],
    #         "actions": ["3", "3"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "61": {
    #         "channel": 1,
    #         "midi": [176, 52, 0, 176],
    #         "actions": ["4", "4"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "62": {
    #         "channel": 1,
    #         "midi": [176, 53, 0, 176],
    #         "actions": ["5", "5"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "63": {
    #         "channel": 1,
    #         "midi": [176, 54, 0, 176],
    #         "actions": ["6", "6"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "64": {
    #         "channel": 1,
    #         "midi": [176, 55, 0, 176],
    #         "actions": ["7", "7"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "65": {
    #         "channel": 1,
    #         "midi": [176, 64, 0, 176],
    #         "actions": ["8", "8"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "66": {
    #         "channel": 1,
    #         "midi": [176, 65, 0, 176],
    #         "actions": ["9", "9"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "67": {
    #         "channel": 1,
    #         "midi": [176, 66, 0, 176],
    #         "actions": ["10", "10"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "68": {
    #         "channel": 1,
    #         "midi": [176, 67, 0, 176],
    #         "actions": ["11", "11"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "69": {
    #         "channel": 1,
    #         "midi": [176, 68, 0, 176],
    #         "actions": ["12", "12"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "70": {
    #         "channel": 1,
    #         "midi": [176, 69, 0, 176],
    #         "actions": ["13", "13"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "71": {
    #         "channel": 1,
    #         "midi": [176, 70, 0, 176],
    #         "actions": ["14", "14"],
    #         "toggle": 0,
    #         "track": 0,
    #     },
    #     "72": {
    #         "channel": 1,
    #         "midi": [176, 71, 0, 176],
    #         "actions": ["15", "15"],
    #         "toggle": 0,
    #         "track": 0,
    #     },

    # },


}



