cl = {
    "name": {
      "Korg nanoKontrol2"
    },
    "leds": {
        "seq_leds": {
            0: [
                176,
                0,
                48,
            ],
            1: [
                176,
                0,
                49,
            ],
            2: [
                176,
                0,
                50,
            ],
            3: [
                176,
                0,
                51,
            ],
            4: [
                176,
                0,
                52,
            ],
            5: [
                176,
                0,
                53,
            ],
            6: [
                176,
                0,
                54,
            ],
            7: [
                176,
                0,
                55,
            ],
            8: [
                176,
                0,
                64,
            ],
            9: [
                176,
                0,
                65,
            ],
            10: [
                176,
                0,
                66,
            ],
            11: [
                176,
                0,
                67,
            ],
            12: [
                176,
                0,
                68,
            ],
            13: [
                176,
                0,
                69,
            ],
            14: [
                176,
                0,
                70,
            ],
            15: [
                176,
                0,
                71,
            ],
        },
        "transport_leds": {
            "stop": [
                176,
                0,
                42,
            ],
            "start": [
                176,
                0,
                41,
            ],
            "record": [
                176,
                0,
                45,
            ],
        },
    },
    "jog_wheel": {},
    "defaults": {
        "octaves": 5,
        "sequence_length": 16,
        "sequence_length": 16,
        "seq_mult": 0,
        "plugin_control": 1,
        "mixer_tracks": 8,
        "Keyboard": 0,
        "Sequencer": 0,
        "keyboard_count": 5,
        "modes": [
            "Buttons",
            "Keyboard",
            "Sequencer",
        ],
        "levels_control_parameter": 1,
        "colors": [-5158821, -6471780, -15521877, -5595116, -15480420],
        "root": "C",
        "scale": "Natural Minor",
        "windows": [
            4,
            0,
            1,
            3,
        ],
    },
    "encoders": {
        "36": {
            "channel": 1,
            "midi": [176, 16, 61, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 1,
        },
        "37": {
            "channel": 1,
            "midi": [176, 17, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 2,
        },
        "38": {
            "channel": 1,
            "midi": [176, 18, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 3,
        },
        "39": {
            "channel": 1,
            "midi": [176, 19, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 3,
        },
        "40": {
            "channel": 1,
            "midi": [176, 20, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 3,
        },
        "41": {
            "channel": 1,
            "midi": [176, 21, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 4,
        },
        "42": {
            "channel": 1,
            "midi": [176, 22, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 5,
        },
        "43": {
            "channel": 1,
            "midi": [176, 23, 0, 176],
            "actions": ["mixer_level", "mixer_pan"],
            "toggle": 0,
            "track": 6,
        },
    },
    "buttons": {
        "1": {
            "channel": 1,
            "midi": [176, 120, 0, 176],
            "actions": ["down", "down"],
            "toggle": 0,
            "track": 0,
        },
        "2": {
            "channel": 1,
            "midi": [176, 59, 0, 176],
            "actions": ["up", "up"],
            "toggle": 0,
            "track": 0,
        },
        "3": {
            "channel": 1,
            "midi": [176, 46, 0, 176],
            "actions": ["change_mode", "change_mode"],
            "toggle": 0,
            "track": 0,
        },
        "4": {
            "channel": 1,
            "midi": [176, 60, 0, 176],
            "actions": ["shift", "shift"],
            "toggle": 0,
            "track": 0,
        },
        "5": {
            "channel": 1,
            "midi": [176, 61, 0, 176],
            "actions": ["rand_pattern", "change_color"],
            "toggle": 0,
            "track": 0,
        },
        "6": {
            "channel": 1,
            "midi": [176, 62, 0, 176],
            "actions": ["rotate_set_windows", "rotate_set_windows"],
            "toggle": 0,
            "track": 0,
        },
        "7": {
            "channel": 1,
            "midi": [176, 43, 0, 176],
            "actions": ["prev_pre_pat", "quantize"],
            "toggle": 0,
            "track": 0,
        },
        "8": {
            "channel": 1,
            "midi": [176, 42, 0, 176],
            "actions": ["next_pre_pat", "save"],
            "toggle": 0,
            "track": 0,
        },
        "9": {
            "channel": 1,
            "midi": [176, 41, 0, 176],
            "actions": ["stop", "stop"],
            "toggle": 0,
            "track": 0,
        },
        "10": {
            "channel": 1,
            "midi": [176, 45, 0, 176],
            "actions": ["start", "start"],
            "toggle": 0,
            "track": 0,
        },
        "11": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["record", "record"],
            "toggle": 0,
            "track": 0,
        },
        "12": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 1,
        },
        "13": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 2,
        },
        "14": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 3,
        },
        "15": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 4,
        },
        "16": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 5,
        },
        "17": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 6,
        },
        "18": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 7,
        },
        "19": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["mixer_solo", "mixer_solo"],
            "toggle": 0,
            "track": 8,
        },
        "20": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 1,
        },
        "21": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 2,
        },
        "22": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 3,
        },
        "23": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 4,
        },
        "24": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 5,
        },
        "25": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 6,
        },
        "26": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 7,
        },
        "27": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["mixer_mute", "mixer_mute"],
            "toggle": 0,
            "track": 8,
        },
        "28": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 1,
        },
        "29": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 2,
        },
        "30": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 3,
        },
        "31": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 4,
        },
        "32": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 5,
        },
        "33": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 6,
        },
        "34": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 7,
        },
        "35": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["mixer_record", "mixer_record"],
            "toggle": 0,
            "track": 8,
        },
    },
    "keyboard": {
        "79": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["C#", ""],
            "toggle": 0,
            "track": 0,
        },
        "80": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["D#", ""],
            "toggle": 0,
            "track": 0,
        },
        "81": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["F#", ""],
            "toggle": 0,
            "track": 0,
        },
        "82": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["G#", ""],
            "toggle": 0,
            "track": 0,
        },
        "83": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["A#", ""],
            "toggle": 0,
            "track": 0,
        },
        "84": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["C", ""],
            "toggle": 0,
            "track": 0,
        },
        "85": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["D", ""],
            "toggle": 0,
            "track": 0,
        },
        "86": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["E", ""],
            "toggle": 0,
            "track": 0,
        },
        "87": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["F", ""],
            "toggle": 0,
            "track": 0,
        },
        "88": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["G", ""],
            "toggle": 0,
            "track": 0,
        },
        "89": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["A", ""],
            "toggle": 0,
            "track": 0,
        },
        "90": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["B", ""],
            "toggle": 0,
            "track": 0,
        },
        "91": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["C#", ""],
            "toggle": 0,
            "track": 1,
        },
        "92": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["D#", ""],
            "toggle": 0,
            "track": 1,
        },
        "93": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["F#", ""],
            "toggle": 0,
            "track": 1,
        },
        "94": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["G#", ""],
            "toggle": 0,
            "track": 1,
        },
        "95": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["A#", ""],
            "toggle": 0,
            "track": 1,
        },
        "96": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["C", ""],
            "toggle": 0,
            "track": 1,
        },
        "97": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["D", ""],
            "toggle": 0,
            "track": 1,
        },
        "98": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["E", ""],
            "toggle": 0,
            "track": 1,
        },
        "99": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["F", ""],
            "toggle": 0,
            "track": 1,
        },
        "100": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["G", ""],
            "toggle": 0,
            "track": 1,
        },
        "101": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["A", ""],
            "toggle": 0,
            "track": 1,
        },
        "102": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["B", ""],
            "toggle": 0,
            "track": 1,
        },
    },
    "sequencer": {
        "44": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["0", "0"],
            "toggle": 0,
            "track": 1,
        },
        "45": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["1", "1"],
            "toggle": 0,
            "track": 1,
        },
        "46": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["2", "2"],
            "toggle": 0,
            "track": 1,
        },
        "47": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["3", "3"],
            "toggle": 0,
            "track": 1,
        },
        "48": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["4", "4"],
            "toggle": 0,
            "track": 1,
        },
        "49": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["5", "5"],
            "toggle": 0,
            "track": 1,
        },
        "50": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["6", "6"],
            "toggle": 0,
            "track": 1,
        },
        "51": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["7", "7"],
            "toggle": 0,
            "track": 1,
        },
        "52": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["8", "8"],
            "toggle": 0,
            "track": 1,
        },
        "53": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["9", "9"],
            "toggle": 0,
            "track": 1,
        },
        "54": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["10", "10"],
            "toggle": 0,
            "track": 1,
        },
        "55": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["11", "11"],
            "toggle": 0,
            "track": 1,
        },
        "56": {
            "channel": 1,
            "midi": [176, 68, 0, 176],
            "actions": ["12", "12"],
            "toggle": 0,
            "track": 1,
        },
        "57": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["13", "13"],
            "toggle": 0,
            "track": 1,
        },
        "58": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["14", "14"],
            "toggle": 0,
            "track": 1,
        },
        "59": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["15", "15"],
            "toggle": 0,
            "track": 1,
        },
    },
    "performance": {
        "103": {
            "channel": 1,
            "midi": [176, 32, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 0,
        },
        "104": {
            "channel": 1,
            "midi": [176, 33, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 1,
        },
        "105": {
            "channel": 1,
            "midi": [176, 34, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 2,
        },
        "106": {
            "channel": 1,
            "midi": [176, 35, 0, 176],
            "actions": ["1", ""],
            "toggle": 0,
            "track": 3,
        },
        "107": {
            "channel": 1,
            "midi": [176, 48, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 0,
        },
        "108": {
            "channel": 1,
            "midi": [176, 49, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 1,
        },
        "109": {
            "channel": 1,
            "midi": [176, 50, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 2,
        },
        "110": {
            "channel": 1,
            "midi": [176, 51, 0, 176],
            "actions": ["2", ""],
            "toggle": 0,
            "track": 3,
        },
        "111": {
            "channel": 1,
            "midi": [176, 64, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 0,
        },
        "112": {
            "channel": 1,
            "midi": [176, 65, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 1,
        },
        "113": {
            "channel": 1,
            "midi": [176, 66, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 2,
        },
        "114": {
            "channel": 1,
            "midi": [176, 67, 0, 176],
            "actions": ["3", ""],
            "toggle": 0,
            "track": 3,
        },
        "115": {
            "channel": 1,
            "midi": [176, 36, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 0,
        },
        "116": {
            "channel": 1,
            "midi": [176, 37, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 1,
        },
        "117": {
            "channel": 1,
            "midi": [176, 38, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 2,
        },
        "118": {
            "channel": 1,
            "midi": [176, 39, 0, 176],
            "actions": ["4", ""],
            "toggle": 0,
            "track": 3,
        },
        "119": {
            "channel": 1,
            "midi": [176, 52, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 0,
        },
        "120": {
            "channel": 1,
            "midi": [176, 53, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 1,
        },
        "121": {
            "channel": 1,
            "midi": [176, 54, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 2,
        },
        "122": {
            "channel": 1,
            "midi": [176, 55, 0, 176],
            "actions": ["5", ""],
            "toggle": 0,
            "track": 3,
        },
        "123": {
            "channel": 1,
            "midi": [176, 22, 71, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 0,
        },
        "124": {
            "channel": 1,
            "midi": [176, 69, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 1,
        },
        "125": {
            "channel": 1,
            "midi": [176, 70, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 2,
        },
        "126": {
            "channel": 1,
            "midi": [176, 71, 0, 176],
            "actions": ["6", ""],
            "toggle": 0,
            "track": 3,
        },
    },
}
