# cl = { "name": "nanoKONTROL2", 

# "leds": { "seq_leds": { }, "transport_leds": {}, },

# "jog_wheel": { },

# "defaults": {   "octaves": 5, "sequence_length": 16, 
#                 "sequence_length": 16, 
#                 "plugin_control": 1, 
#                 "mixer_tracks": 8, 
#                 "Keyboard": 0, 
#                 "Sequencer": 0, 
#                 "keyboard_count": 5, 
#                 "modes": ["Buttons", "Keyboard", "Sequencer", ], 
#                 "levels_control_parameter": 1, 
#                 "colors": [], 
#                 "root": "C", 
#                 "scale": "Major", 
#                 "windows": [4, 0, 2, 1, 3, ] },

# "encoders": { '36': {'channel': 1, 'midi': [176, 16, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 1 }, '37': {'channel': 1, 'midi': [176, 17, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 2 }, '38': {'channel': 1, 'midi': [176, 18, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 3 }, '39': {'channel': 1, 'midi': [176, 19, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 4 }, '40': {'channel': 1, 'midi': [176, 20, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 5 }, '41': {'channel': 1, 'midi': [176, 21, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 6 }, '42': {'channel': 1, 'midi': [176, 22, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 7 }, '43': {'channel': 1, 'midi': [176, 23, 0, 176], 'actions': ['mixer_pan', 'selected_level'], 'toggle': 0, 'track': 8 }, '44': {'channel': 1, 'midi': [176, 0, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 1 }, '45': {'channel': 1, 'midi': [176, 1, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 2 }, '46': {'channel': 1, 'midi': [176, 2, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 3 }, '47': {'channel': 1, 'midi': [176, 3, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 4 }, '48': {'channel': 1, 'midi': [176, 4, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 5 }, '49': {'channel': 1, 'midi': [176, 5, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 6 }, '50': {'channel': 1, 'midi': [176, 6, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 7 }, '51': {'channel': 1, 'midi': [176, 7, 0, 176], 'actions': ['mixer_level', 'selected_level'], 'toggle': 0, 'track': 8 }, },

# "buttons": { '1': {'channel': 1, 'midi': [176, 120, 0, 176], 'actions': ['zoom_horz', 'zoom_vert'], 'toggle': 0, 'track': 0 }, '2': {'channel': 1, 'midi': [176, 59, 0, 176], 'actions': ['right', 'start'], 'toggle': 0, 'track': 0 }, '3': {'channel': 1, 'midi': [176, 46, 0, 176], 'actions': ['shift', 'shift'], 'toggle': 0, 'track': 0 }, '4': {'channel': 1, 'midi': [176, 60, 0, 176], 'actions': ['rotate_set_windows', 'rotate_set_windows'], 'toggle': 0, 'track': 0 }, '5': {'channel': 1, 'midi': [176, 61, 0, 176], 'actions': ['rand_trigs', 'rand_pattern'], 'toggle': 0, 'track': 0 }, '6': {'channel': 1, 'midi': [176, 62, 0, 176], 'actions': ['copy', 'paste'], 'toggle': 0, 'track': 0 }, '7': {'channel': 1, 'midi': [176, 43, 0, 176], 'actions': ['open_channel', 'start'], 'toggle': 0, 'track': 0 }, '8': {'channel': 1, 'midi': [176, 44, 0, 176], 'actions': ['change_mode', 'start'], 'toggle': 0, 'track': 0 }, '9': {'channel': 1, 'midi': [176, 42, 0, 176], 'actions': ['stop', 'stop'], 'toggle': 0, 'track': 0 }, '10': {'channel': 1, 'midi': [176, 41, 0, 176], 'actions': ['start', 'start'], 'toggle': 0, 'track': 0 }, '11': {'channel': 1, 'midi': [176, 45, 0, 176], 'actions': ['record', 'record'], 'toggle': 0, 'track': 0 }, '12': {'channel': 1, 'midi': [176, 32, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 1 }, '13': {'channel': 1, 'midi': [176, 33, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 2 }, '14': {'channel': 1, 'midi': [176, 34, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 3 }, '15': {'channel': 1, 'midi': [176, 35, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 4 }, '16': {'channel': 1, 'midi': [176, 36, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 5 }, '17': {'channel': 1, 'midi': [176, 37, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 6 }, '18': {'channel': 1, 'midi': [176, 38, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 7 }, '19': {'channel': 1, 'midi': [176, 39, 0, 176], 'actions': ['mixer_solo', 'start'], 'toggle': 0, 'track': 8 }, '20': {'channel': 1, 'midi': [176, 48, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 1 }, '21': {'channel': 1, 'midi': [176, 49, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 2 }, '22': {'channel': 1, 'midi': [176, 50, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 3 }, '23': {'channel': 1, 'midi': [176, 51, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 4 }, '24': {'channel': 1, 'midi': [176, 52, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 5 }, '25': {'channel': 1, 'midi': [176, 53, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 6 }, '26': {'channel': 1, 'midi': [176, 54, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 7 }, '27': {'channel': 1, 'midi': [176, 55, 0, 176], 'actions': ['mixer_mute', 'start'], 'toggle': 0, 'track': 8 }, '28': {'channel': 1, 'midi': [176, 64, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 1 }, '29': {'channel': 1, 'midi': [176, 65, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 2 }, '30': {'channel': 1, 'midi': [176, 66, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 3 }, '31': {'channel': 1, 'midi': [176, 67, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 4 }, '32': {'channel': 1, 'midi': [176, 68, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 5 }, '33': {'channel': 1, 'midi': [176, 69, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 6 }, '34': {'channel': 1, 'midi': [176, 70, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 7 }, '35': {'channel': 1, 'midi': [176, 71, 0, 176], 'actions': ['mixer_record', 'start'], 'toggle': 0, 'track': 8 }, },

# "keyboard": { '52': {'channel': 1, 'midi': [176, 33, 0, 176], 'actions': ['C#', ''], 'toggle': 0, 'track': 0 }, '53': {'channel': 1, 'midi': [176, 35, 0, 176], 'actions': ['D#', ''], 'toggle': 0, 'track': 0 }, '54': {'channel': 1, 'midi': [176, 38, 0, 176], 'actions': ['F#', ''], 'toggle': 0, 'track': 0 }, '55': {'channel': 1, 'midi': [176, 48, 0, 176], 'actions': ['G#', ''], 'toggle': 0, 'track': 0 }, '56': {'channel': 1, 'midi': [176, 50, 0, 176], 'actions': ['A#', ''], 'toggle': 0, 'track': 0 }, '57': {'channel': 1, 'midi': [176, 32, 0, 176], 'actions': ['C', ''], 'toggle': 0, 'track': 0 }, '58': {'channel': 1, 'midi': [176, 34, 0, 176], 'actions': ['D', ''], 'toggle': 0, 'track': 0 }, '59': {'channel': 1, 'midi': [176, 36, 0, 176], 'actions': ['E', ''], 'toggle': 0, 'track': 0 }, '60': {'channel': 1, 'midi': [176, 37, 0, 176], 'actions': ['F', ''], 'toggle': 0, 'track': 0 }, '61': {'channel': 1, 'midi': [176, 39, 0, 176], 'actions': ['G', ''], 'toggle': 0, 'track': 0 }, '62': {'channel': 1, 'midi': [176, 49, 0, 176], 'actions': ['A', ''], 'toggle': 0, 'track': 0 }, '63': {'channel': 1, 'midi': [176, 51, 0, 176], 'actions': ['B', ''], 'toggle': 0, 'track': 0 }, '64': {'channel': 1, 'midi': [176, 53, 0, 176], 'actions': ['C#', ''], 'toggle': 0, 'track': 0 }, '65': {'channel': 1, 'midi': [176, 55, 0, 176], 'actions': ['D#', ''], 'toggle': 0, 'track': 0 }, '66': {'channel': 1, 'midi': [176, 68, 0, 176], 'actions': ['F#', ''], 'toggle': 0, 'track': 0 }, '67': {'channel': 1, 'midi': [176, 69, 0, 176], 'actions': ['G#', ''], 'toggle': 0, 'track': 0 }, '68': {'channel': 1, 'midi': [176, 71, 0, 176], 'actions': ['A#', ''], 'toggle': 0, 'track': 0 }, '69': {'channel': 1, 'midi': [176, 52, 0, 176], 'actions': ['C', ''], 'toggle': 0, 'track': 0 }, '70': {'channel': 1, 'midi': [176, 64, 0, 176], 'actions': ['D', ''], 'toggle': 0, 'track': 0 }, '71': {'channel': 1, 'midi': [176, 65, 0, 176], 'actions': ['E', ''], 'toggle': 0, 'track': 0 }, '72': {'channel': 1, 'midi': [176, 66, 0, 176], 'actions': ['F', ''], 'toggle': 0, 'track': 0 }, '73': {'channel': 1, 'midi': [176, 68, 0, 176], 'actions': ['G', ''], 'toggle': 0, 'track': 0 }, '74': {'channel': 1, 'midi': [176, 70, 0, 176], 'actions': ['A', ''], 'toggle': 0, 'track': 0 }, },

# "sequencer": { '100': {'channel': 1, 'midi': [176, 32, 0, 176], 'actions': ['select_pattern', '0'], 'toggle': 0, 'track': 1 }, '101': {'channel': 1, 'midi': [176, 33, 0, 176], 'actions': ['select_pattern', '1'], 'toggle': 0, 'track': 2 }, '102': {'channel': 1, 'midi': [176, 34, 0, 176], 'actions': ['select_pattern', '2'], 'toggle': 0, 'track': 3 }, '103': {'channel': 1, 'midi': [176, 35, 0, 176], 'actions': ['select_pattern', '3'], 'toggle': 0, 'track': 4 }, '104': {'channel': 1, 'midi': [176, 36, 0, 176], 'actions': ['select_pattern', '4'], 'toggle': 0, 'track': 5 }, '105': {'channel': 1, 'midi': [176, 37, 0, 176], 'actions': ['select_pattern', '5'], 'toggle': 0, 'track': 6 }, '106': {'channel': 1, 'midi': [176, 38, 0, 176], 'actions': ['select_pattern', '6'], 'toggle': 0, 'track': 7 }, '107': {'channel': 1, 'midi': [176, 39, 0, 176], 'actions': ['select_pattern', '7'], 'toggle': 0, 'track': 8 }, '108': {'channel': 1, 'midi': [176, 48, 0, 176], 'actions': ['0', '0'], 'toggle': 0, 'track': 1 }, '109': {'channel': 1, 'midi': [176, 49, 0, 176], 'actions': ['1', '1'], 'toggle': 0, 'track': 1 }, '110': {'channel': 1, 'midi': [176, 50, 0, 176], 'actions': ['2', '2'], 'toggle': 0, 'track': 1 }, '111': {'channel': 1, 'midi': [176, 51, 0, 176], 'actions': ['3', '3'], 'toggle': 0, 'track': 1 }, '112': {'channel': 1, 'midi': [176, 52, 0, 176], 'actions': ['4', '4'], 'toggle': 0, 'track': 1 }, '113': {'channel': 1, 'midi': [176, 53, 0, 176], 'actions': ['5', '5'], 'toggle': 0, 'track': 1 }, '114': {'channel': 1, 'midi': [176, 54, 0, 176], 'actions': ['6', '6'], 'toggle': 0, 'track': 1 }, '115': {'channel': 1, 'midi': [176, 55, 0, 176], 'actions': ['7', '7'], 'toggle': 0, 'track': 1 }, '116': {'channel': 1, 'midi': [176, 64, 0, 176], 'actions': ['8', '8'], 'toggle': 0, 'track': 1 }, '117': {'channel': 1, 'midi': [176, 65, 0, 176], 'actions': ['9', '9'], 'toggle': 0, 'track': 1 }, '118': {'channel': 1, 'midi': [176, 66, 0, 176], 'actions': ['10', '10'], 'toggle': 0, 'track': 1 }, '119': {'channel': 1, 'midi': [176, 67, 0, 176], 'actions': ['10', '11'], 'toggle': 0, 'track': 1 }, '120': {'channel': 1, 'midi': [176, 68, 0, 176], 'actions': ['12', '12'], 'toggle': 0, 'track': 1 }, '121': {'channel': 1, 'midi': [176, 69, 0, 176], 'actions': ['13', '13'], 'toggle': 0, 'track': 1 }, '122': {'channel': 1, 'midi': [176, 70, 0, 176], 'actions': ['14', '14'], 'toggle': 0, 'track': 1 }, '123': {'channel': 1, 'midi': [176, 71, 0, 176], 'actions': ['15', '15'], 'toggle': 0, 'track': 1 }, },

# "performance": { 
#         '76': {'channel': 1, 'midi': [176, 32, 0, 176], 'actions': ['1', ''], 'toggle': 0, 'track': 0 }, 
#         '77': {'channel': 1, 'midi': [176, 33, 0, 176], 'actions': ['1', ''], 'toggle': 0, 'track': 1 }, 
#         '78': {'channel': 1, 'midi': [176, 34, 0, 176], 'actions': ['1', ''], 'toggle': 0, 'track': 2 }, 
#         '79': {'channel': 1, 'midi': [176, 35, 0, 176], 'actions': ['1', ''], 'toggle': 0, 'track': 3 }, 
#         '80': {'channel': 1, 'midi': [176, 48, 0, 176], 'actions': ['2', ''], 'toggle': 0, 'track': 0 }, 
#         '81': {'channel': 1, 'midi': [176, 49, 0, 176], 'actions': ['2', ''], 'toggle': 0, 'track': 1 }, 
#         '82': {'channel': 1, 'midi': [176, 50, 0, 176], 'actions': ['2', ''], 'toggle': 0, 'track': 2 }, 
#         '83': {'channel': 1, 'midi': [176, 51, 0, 176], 'actions': ['2', ''], 'toggle': 0, 'track': 3 }, 
#         '84': {'channel': 1, 'midi': [176, 64, 0, 176], 'actions': ['3', ''], 'toggle': 0, 'track': 0 }, 
#         '85': {'channel': 1, 'midi': [176, 65, 0, 176], 'actions': ['3', ''], 'toggle': 0, 'track': 1 }, '86': {'channel': 1, 'midi': [176, 66, 0, 176], 'actions': ['3', ''], 'toggle': 0, 'track': 2 }, '87': {'channel': 1, 'midi': [176, 67, 0, 176], 'actions': ['3', ''], 'toggle': 0, 'track': 3 }, '88': {'channel': 1, 'midi': [176, 36, 0, 176], 'actions': ['4', ''], 'toggle': 0, 'track': 0 }, '89': {'channel': 1, 'midi': [176, 37, 0, 176], 'actions': ['4', ''], 'toggle': 0, 'track': 1 }, '90': {'channel': 1, 'midi': [176, 38, 0, 176], 'actions': ['4', ''], 'toggle': 0, 'track': 2 }, '91': {'channel': 1, 'midi': [176, 39, 0, 176], 'actions': ['4', ''], 'toggle': 0, 'track': 3 }, '92': {'channel': 1, 'midi': [176, 52, 0, 176], 'actions': ['5', ''], 'toggle': 0, 'track': 0 }, '93': {'channel': 1, 'midi': [176, 53, 0, 176], 'actions': ['5', ''], 'toggle': 0, 'track': 1 }, '94': {'channel': 1, 'midi': [176, 54, 0, 176], 'actions': ['5', ''], 'toggle': 0, 'track': 2 }, '95': {'channel': 1, 'midi': [176, 55, 0, 176], 'actions': ['5', ''], 'toggle': 0, 'track': 3 }, '96': {'channel': 1, 'midi': [176, 68, 0, 176], 'actions': ['6', ''], 'toggle': 0, 'track': 0 }, '97': {'channel': 1, 'midi': [176, 69, 0, 176], 'actions': ['6', ''], 'toggle': 0, 'track': 1 }, '98': {'channel': 1, 'midi': [176, 70, 0, 176], 'actions': ['6', ''], 'toggle': 0, 'track': 2 }, '99': {'channel': 1, 'midi': [176, 71, 0, 176], 'actions': ['6', ''], 'toggle': 0, 'track': 3 }, }, }
cl = {"name": "ATM SQ",

      "leds": {"seq_leds": {}, "transport_leds": {}, },

      "jog_wheel": {
          '34': {'channel': 1, 'midi': [176, 60, 1, 176], 'actions': ['jog_wheel_up', 'zoom_in_vert'], 'toggle': 0, 'track': 0},
          '35': {'channel': 1, 'midi': [176, 60, 65, 176], 'actions': ['jog_wheel_down', 'zoom_out_vert'], 'toggle': 0, 'track': 0}, 
          '135': {'channel': 1, 'midi': [144, 98, 127, 176], 'actions': ['zoom_in_horz', 'zoom_in_vert'], 'toggle': 0, 'track': 0}, 
          '137': {'channel': 1, 'midi': [144, 99, 127, 176], 'actions': ['zoom_out_horz', 'zoom_out_vert'], 'toggle': 0, 'track': 0}, },

      "defaults": {"octaves": 5, "sequence_length": 16, "sequence_length": 16, "plugin_control": 1, "mixer_tracks": 1,
                   "Keyboard": 0, "Sequencer": 0, "keyboard_count": 5, "modes": ["Buttons", "Keyboard", "Sequencer", ],
                   "levels_control_parameter": 1, "colors": [], "root": "C", "scale": "Major",
                   "windows": [4, 0, 2, 1, 3, ]},

      "encoders": {
          '25': {'channel': 1, 'midi': [176, 1, 19, 176], 'actions': ['selected_level', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '26': {'channel': 1, 'midi': [176, 15, 0, ], 'actions': ['selected_level', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '27': {'channel': 1, 'midi': [176, 16, 0, ], 'actions': ['selected_level', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '28': {'channel': 1, 'midi': [176, 17, 0, ], 'actions': ['selected_level', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '29': {'channel': 1, 'midi': [176, 18, 0, ], 'actions': ['selected_level', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '30': {'channel': 1, 'midi': [176, 19, 0, ], 'actions': ['selected_pan', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '31': {'channel': 1, 'midi': [176, 20, 0, ], 'actions': ['set_efx_track', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '32': {'channel': 1, 'midi': [176, 21, 0, ], 'actions': ['set_random_offset', 'selected_level'], 'toggle': 0,
                 'track': 0},
          '33': {'channel': 1, 'midi': [176, 1, 54, 176], 'actions': ['selected_level', 'selected_level'], 'toggle': 0,
                 'track': 0}, },

      "buttons": {
          '1': {'channel': 1, 'midi': [176, 24, 0, 176], 'actions': ['change_mode', 'start'], 'toggle': 0, 'track': 0},
          '2': {'channel': 1, 'midi': [176, 25, 0, 176], 'actions': ['change_color', 'start'], 'toggle': 0, 'track': 0},
          '3': {'channel': 1, 'midi': [176, 26, 0, 176], 'actions': ['increment_scale', 'set_root_note'], 'toggle': 0,
                'track': 0},
          '4': {'channel': 1, 'midi': [176, 27, 0, 176], 'actions': ['enter', 'start'], 'toggle': 0, 'track': 0},
          '5': {'channel': 1, 'midi': [176, 28, 0, 176], 'actions': ['shift', 'shift'], 'toggle': 0, 'track': 0},
          '6': {'channel': 1, 'midi': [176, 29, 0, 176], 'actions': ['rand_pattern', 'start'], 'toggle': 0, 'track': 0},
          '7': {'channel': 1, 'midi': [176, 30, 0, 176], 'actions': ['rand_trigs', 'start'], 'toggle': 0, 'track': 0},
          '8': {'channel': 1, 'midi': [176, 31, 0, 176], 'actions': ['rotate_set_windows', 'start'], 'toggle': 0,
                'track': 0},
          '9': {'channel': 1, 'midi': [144, 93, 0, 144], 'actions': ['stop', 'start'], 'toggle': 0, 'track': 0},
          '10': {'channel': 1, 'midi': [144, 94, 0, 144], 'actions': ['start', 'start'], 'toggle': 0, 'track': 0},
          '11': {'channel': 1, 'midi': [144, 95, 0, 144], 'actions': ['record', 'start'], 'toggle': 0, 'track': 0},
          '12': {'channel': 1, 'midi': [144, 89, 0, 144], 'actions': ['shift', 'shift'], 'toggle': 0, 'track': 0},
          '15': {'channel': 1, 'midi': [144, 14, 0, 144], 'actions': ['solo', 'start'], 'toggle': 0, 'track': 0},
          '16': {'channel': 1, 'midi': [144, 22, 0, 144], 'actions': ['mute', 'start'], 'toggle': 0, 'track': 0},
          '17': {'channel': 1, 'midi': [144, 6, 0, 144], 'actions': ['arm_track', 'start'], 'toggle': 0, 'track': 0},
          '18': {'channel': 1, 'midi': [144, 100, 0, 144], 'actions': ['open_channel', 'start'], 'toggle': 0,
                 'track': 0},
          '19': {'channel': 1, 'midi': [144, 42, 0, 176], 'actions': ['start', 'start'], 'toggle': 0, 'track': 0},
          '20': {'channel': 1, 'midi': [144, 43, 0, 176], 'actions': ['start', 'start'], 'toggle': 0, 'track': 0},
          '21': {'channel': 1, 'midi': [144, 30, 0, 144], 'actions': ['up', 'start'], 'toggle': 0, 'track': 0},
          # '22': {'channel': 1, 'midi': [144, 98, 0, 144], 'actions': ['left', 'start'], 'toggle': 0, 'track': 0},
          '23': {'channel': 1, 'midi': [144, 31, 0, 144], 'actions': ['down', 'start'], 'toggle': 0, 'track': 0},
          # '24': {'channel': 1, 'midi': [144, 99, 0, 144], 'actions': ['right', 'start'], 'toggle': 0, 'track': 0}, 
          },

      "keyboard": {'98': {'channel': 10, 'midi': [144, 49, 0, 128], 'actions': ['C#', ''], 'toggle': 0, 'track': 0},
                   '99': {'channel': 10, 'midi': [144, 51, 0, 128], 'actions': ['D#', ''], 'toggle': 0, 'track': 0},
                   '100': {'channel': 10, 'midi': [144, 54, 0, 128], 'actions': ['F#', ''], 'toggle': 0, 'track': 0},
                   '101': {'channel': 10, 'midi': [144, 56, 0, 128], 'actions': ['G#', ''], 'toggle': 0, 'track': 0},
                   '102': {'channel': 10, 'midi': [144, 58, 0, 128], 'actions': ['A#', ''], 'toggle': 0, 'track': 0},
                   '103': {'channel': 10, 'midi': [144, 48, 0, 128], 'actions': ['C', ''], 'toggle': 0, 'track': 0},
                   '104': {'channel': 10, 'midi': [144, 50, 0, 128], 'actions': ['D', ''], 'toggle': 0, 'track': 0},
                   '105': {'channel': 10, 'midi': [144, 52, 0, 128], 'actions': ['E', ''], 'toggle': 0, 'track': 0},
                   '106': {'channel': 10, 'midi': [144, 53, 0, 128], 'actions': ['F', ''], 'toggle': 0, 'track': 0},
                   '107': {'channel': 10, 'midi': [144, 55, 0, 128], 'actions': ['G', ''], 'toggle': 0, 'track': 0},
                   '108': {'channel': 10, 'midi': [144, 57, 0, 128], 'actions': ['A', ''], 'toggle': 0, 'track': 0},
                   '109': {'channel': 10, 'midi': [144, 72, 0, 128], 'actions': ['B', ''], 'toggle': 0, 'track': 0},
                   '110': {'channel': 10, 'midi': [144, 61, 0, 128], 'actions': ['C#', ''], 'toggle': 0, 'track': 1},
                   '111': {'channel': 10, 'midi': [144, 63, 0, 128], 'actions': ['D#', ''], 'toggle': 0, 'track': 1},
                   '112': {'channel': 10, 'midi': [144, 66, 0, 128], 'actions': ['F#', ''], 'toggle': 0, 'track': 1},
                   '113': {'channel': 10, 'midi': [144, 68, 0, 128], 'actions': ['G#', ''], 'toggle': 0, 'track': 1},
                   '114': {'channel': 10, 'midi': [144, 70, 0, 128], 'actions': ['A#', ''], 'toggle': 0, 'track': 1},
                   '115': {'channel': 10, 'midi': [144, 60, 0, 128], 'actions': ['C', ''], 'toggle': 0, 'track': 1},
                   '116': {'channel': 10, 'midi': [144, 62, 0, 128], 'actions': ['D', ''], 'toggle': 0, 'track': 1},
                   '117': {'channel': 10, 'midi': [144, 64, 0, 128], 'actions': ['E', ''], 'toggle': 0, 'track': 1},
                   '118': {'channel': 10, 'midi': [144, 65, 0, 128], 'actions': ['F', ''], 'toggle': 0, 'track': 1},
                   '119': {'channel': 10, 'midi': [144, 67, 0, 128], 'actions': ['G', ''], 'toggle': 0, 'track': 1},
                   '120': {'channel': 10, 'midi': [144, 69, 0, 128], 'actions': ['A', ''], 'toggle': 0, 'track': 1},
                   '121': {'channel': 10, 'midi': [144, 71, 0, 128], 'actions': ['B', ''], 'toggle': 0, 'track': 1},
                   '122': {'channel': 10, 'midi': [144, 73, 0, 128], 'actions': ['C#', ''], 'toggle': 0, 'track': 2},
                   '127': {'channel': 10, 'midi': [144, 72, 0, 128], 'actions': ['C', ''], 'toggle': 0, 'track': 2},
                   '128': {'channel': 10, 'midi': [144, 74, 0, 128], 'actions': ['D', ''], 'toggle': 0, 'track': 2}, },

      "sequencer": {
          '68': {'channel': 10, 'midi': [144, 52, 0, 128], 'actions': ['Select Pattern * ', 'Select Pattern *'],
                 'toggle': 0, 'track': 1},
          '69': {'channel': 10, 'midi': [144, 53, 0, 128], 'actions': ['Select Pattern * ', '1'], 'toggle': 0,
                 'track': 2},
          '70': {'channel': 10, 'midi': [144, 54, 0, 128], 'actions': ['Select Pattern * ', '2'], 'toggle': 0,
                 'track': 3},
          '71': {'channel': 10, 'midi': [144, 55, 0, 128], 'actions': ['Select Pattern * ', '3'], 'toggle': 0,
                 'track': 4},
          '72': {'channel': 10, 'midi': [144, 56, 0, 128], 'actions': ['Select Pattern * ', '4'], 'toggle': 0,
                 'track': 5},
          '73': {'channel': 10, 'midi': [144, 57, 0, 128], 'actions': ['Select Pattern * ', '5'], 'toggle': 0,
                 'track': 6},
          '74': {'channel': 10, 'midi': [144, 58, 0, 128], 'actions': ['Select Pattern * ', '6'], 'toggle': 0,
                 'track': 7},
          '75': {'channel': 10, 'midi': [144, 59, 0, 128], 'actions': ['Select Pattern * ', '7'], 'toggle': 0,
                 'track': 8},
          '76': {'channel': 10, 'midi': [144, 60, 0, 128], 'actions': ['Select Pattern * ', '8'], 'toggle': 0,
                 'track': 9},
          '77': {'channel': 10, 'midi': [144, 61, 0, 128], 'actions': ['Select Pattern * ', '9'], 'toggle': 0,
                 'track': 10},
          '78': {'channel': 10, 'midi': [144, 62, 0, 128], 'actions': ['Select Pattern * ', '10'], 'toggle': 0,
                 'track': 11},
          '79': {'channel': 10, 'midi': [144, 63, 0, 128], 'actions': ['Select Pattern * ', '11'], 'toggle': 0,
                 'track': 12},
          '80': {'channel': 10, 'midi': [144, 64, 0, 128], 'actions': ['Select Pattern * ', '12'], 'toggle': 0,
                 'track': 13},
          '81': {'channel': 10, 'midi': [144, 65, 0, 128], 'actions': ['Select Pattern * ', '13'], 'toggle': 0,
                 'track': 14},
          '82': {'channel': 10, 'midi': [144, 66, 0, 128], 'actions': ['Select Pattern * ', '14'], 'toggle': 0,
                 'track': 15},
          '83': {'channel': 10, 'midi': [144, 67, 0, 128], 'actions': ['Select Pattern * ', '15'], 'toggle': 0,
                 'track': 16},
          '84': {'channel': 10, 'midi': [144, 36, 0, 128], 'actions': ['0', '0'], 'toggle': 0, 'track': 1},
          '85': {'channel': 10, 'midi': [144, 37, 0, 128], 'actions': ['1', '1'], 'toggle': 0, 'track': 1},
          '86': {'channel': 10, 'midi': [144, 38, 0, 128], 'actions': ['2', '2'], 'toggle': 0, 'track': 1},
          '87': {'channel': 10, 'midi': [144, 39, 0, 128], 'actions': ['3', '3'], 'toggle': 0, 'track': 1},
          '88': {'channel': 10, 'midi': [144, 40, 0, 128], 'actions': ['4', '4'], 'toggle': 0, 'track': 1},
          '89': {'channel': 10, 'midi': [144, 41, 0, 128], 'actions': ['5', '5'], 'toggle': 0, 'track': 1},
          '90': {'channel': 10, 'midi': [144, 42, 0, 128], 'actions': ['6', '6'], 'toggle': 0, 'track': 1},
          '91': {'channel': 10, 'midi': [144, 43, 0, 128], 'actions': ['7', '7'], 'toggle': 0, 'track': 1},
          '92': {'channel': 10, 'midi': [144, 44, 0, 128], 'actions': ['8', '8'], 'toggle': 0, 'track': 1},
          '93': {'channel': 10, 'midi': [144, 45, 0, 128], 'actions': ['9', '9'], 'toggle': 0, 'track': 1},
          '94': {'channel': 10, 'midi': [144, 46, 0, 128], 'actions': ['10', '10'], 'toggle': 0, 'track': 1},
          '95': {'channel': 10, 'midi': [144, 47, 0, 128], 'actions': ['11', '11'], 'toggle': 0, 'track': 1},
          '96': {'channel': 10, 'midi': [144, 48, 0, 128], 'actions': ['12', '12'], 'toggle': 0, 'track': 1},
          '97': {'channel': 10, 'midi': [144, 49, 0, 128], 'actions': ['13', '13'], 'toggle': 0, 'track': 1},
          '98': {'channel': 10, 'midi': [144, 50, 0, 128], 'actions': ['14', '14'], 'toggle': 0, 'track': 1},
          '99': {'channel': 10, 'midi': [144, 51, 0, 128], 'actions': ['15', '15'], 'toggle': 0, 'track': 1}, },

      "performance": {'36': {'channel': 10, 'midi': [144, 44, 0, 128], 'actions': ['1', ''], 'toggle': 0, 'track': 0},
                      '37': {'channel': 10, 'midi': [144, 45, 0, 128], 'actions': ['1', ''], 'toggle': 0, 'track': 1},
                      '38': {'channel': 10, 'midi': [144, 46, 0, 128], 'actions': ['1', ''], 'toggle': 0, 'track': 2},
                      '39': {'channel': 10, 'midi': [144, 47, 0, 128], 'actions': ['1', ''], 'toggle': 0, 'track': 3},
                      '40': {'channel': 10, 'midi': [144, 36, 0, 128], 'actions': ['2', ''], 'toggle': 0, 'track': 0},
                      '41': {'channel': 10, 'midi': [144, 37, 0, 128], 'actions': ['2', ''], 'toggle': 0, 'track': 1},
                      '42': {'channel': 10, 'midi': [144, 38, 0, 128], 'actions': ['2', ''], 'toggle': 0, 'track': 2},
                      '43': {'channel': 10, 'midi': [144, 39, 0, 128], 'actions': ['2', ''], 'toggle': 0, 'track': 3},
                      '44': {'channel': 10, 'midi': [144, 48, 0, 128], 'actions': ['3', ''], 'toggle': 0, 'track': 0},
                      '45': {'channel': 10, 'midi': [144, 49, 0, 128], 'actions': ['3', ''], 'toggle': 0, 'track': 1},
                      '46': {'channel': 10, 'midi': [144, 50, 0, 128], 'actions': ['3', ''], 'toggle': 0, 'track': 2},
                      '47': {'channel': 10, 'midi': [144, 51, 0, 128], 'actions': ['3', ''], 'toggle': 0, 'track': 3},
                      '48': {'channel': 10, 'midi': [144, 40, 0, 128], 'actions': ['4', ''], 'toggle': 0, 'track': 0},
                      '49': {'channel': 10, 'midi': [144, 41, 0, 128], 'actions': ['4', ''], 'toggle': 0, 'track': 1},
                      '50': {'channel': 10, 'midi': [144, 42, 0, 128], 'actions': ['4', ''], 'toggle': 0, 'track': 2},
                      '51': {'channel': 10, 'midi': [144, 43, 0, 128], 'actions': ['4', ''], 'toggle': 0, 'track': 3},
                      '52': {'channel': 10, 'midi': [144, 60, 0, 128], 'actions': ['5', ''], 'toggle': 0, 'track': 0},
                      '53': {'channel': 10, 'midi': [144, 61, 0, 128], 'actions': ['5', ''], 'toggle': 0, 'track': 1},
                      '54': {'channel': 10, 'midi': [144, 62, 0, 128], 'actions': ['5', ''], 'toggle': 0, 'track': 2},
                      '55': {'channel': 10, 'midi': [144, 63, 0, 128], 'actions': ['5', ''], 'toggle': 0, 'track': 3},
                      '56': {'channel': 10, 'midi': [144, 52, 0, 128], 'actions': ['6', ''], 'toggle': 0, 'track': 0},
                      '57': {'channel': 10, 'midi': [144, 53, 0, 128], 'actions': ['6', ''], 'toggle': 0, 'track': 1},
                      '58': {'channel': 10, 'midi': [144, 54, 0, 128], 'actions': ['6', ''], 'toggle': 0, 'track': 2},
                      '59': {'channel': 10, 'midi': [144, 55, 0, 128], 'actions': ['6', ''], 'toggle': 0, 'track': 3},
                      '60': {'channel': 10, 'midi': [144, 64, 0, 128], 'actions': ['7', ''], 'toggle': 0, 'track': 0},
                      '61': {'channel': 10, 'midi': [144, 65, 0, 128], 'actions': ['7', ''], 'toggle': 0, 'track': 1},
                      '62': {'channel': 10, 'midi': [144, 66, 0, 128], 'actions': ['7', ''], 'toggle': 0, 'track': 2},
                      '63': {'channel': 10, 'midi': [144, 67, 0, 128], 'actions': ['7', ''], 'toggle': 0, 'track': 3},
                      '64': {'channel': 10, 'midi': [144, 56, 0, 128], 'actions': ['8', ''], 'toggle': 0, 'track': 0},
                      '65': {'channel': 10, 'midi': [144, 57, 0, 128], 'actions': ['8', ''], 'toggle': 0, 'track': 1},
                      '66': {'channel': 10, 'midi': [144, 58, 0, 128], 'actions': ['8', ''], 'toggle': 0, 'track': 2},
                      '67': {'channel': 10, 'midi': [144, 59, 0, 128], 'actions': ['8', ''], 'toggle': 0,
                             'track': 3}, }, }

# # # cl = {
# # #     "name": "nanokontrol2",
# # # "leds": { "seq_leds": { 
# # #                 1: [ 176, 0, 49, ], 
# # #                 2: [ 176, 0, 50, ], 
# # #                 3: [ 176, 0, 51, ], 
# # #                 4: [ 176, 0, 52, ], 
# # #                 5: [ 176, 0, 53, ], 
# # #                 6: [ 176, 0, 54, ], 
# # #                 7: [ 176, 0, 55, ], 
# # #                 8: [ 176, 0, 56, ], 
# # #                 9: [ 176, 0, 64, ], 
# # #                 10: [ 176, 0, 65, ], 
# # #                 11: [ 176, 0, 66, ], 
# # #                 12: [ 176, 0, 67, ], 
# # #                 13: [ 176, 0, 68, ], 
# # #                 14: [ 176, 0, 69, ], 
# # #                 15: [ 176, 0, 70, ],
# # #                 16: [ 176, 0, 71, ],  }, 
# # #             "transport_leds": {
# # #                 "stop":     [ 176, 0, 42, ], 
# # #                 "start":    [ 176, 0, 41, ], 
# # #                 "record":   [ 176, 0, 45, ], 
                 
# # #                 }, 
# # #         },
# # #     "jog_wheel": {},
# # #     "defaults": {
# # #         "octaves": 5,
# # #         "sequence_length": 16,
# # #         "sequence_length": 16,
# # #         "seq_mult": 0,
# # #         "plugin_control": 1,
# # #         "mixer_tracks": 1,
# # #         "Keyboard": 0,
# # #         "Sequencer": 0,
# # #         "keyboard_count": 5,
# # #         "modes": [
# # #             "Buttons",
# # #             "Keyboard",
# # #             "Sequencer",
# # #         ],
# # #         "levels_control_parameter": 1,
# # #         "colors": [],
# # #         "root": "C",
# # #         "scale": "Major",
# # #         "windows": [
# # #             4,
# # #             0,
# # #             2,
# # #             1,
# # #             3,
# # #         ],
# # #     },
# # #     "encoders": {
# # #         "1": {
# # #             "channel": 1,
# # #             "midi": [176, 16, 69, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "2": {
# # #             "channel": 1,
# # #             "midi": [176, 17, 0, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "3": {
# # #             "channel": 1,
# # #             "midi": [176, 18, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "4": {
# # #             "channel": 1,
# # #             "midi": [176, 19, 0, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 4,
# # #         },
# # #         "5": {
# # #             "channel": 1,
# # #             "midi": [176, 20, 0, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 5,
# # #         },
# # #         "6": {
# # #             "channel": 1,
# # #             "midi": [176, 21, 0, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 6,
# # #         },
# # #         "7": {
# # #             "channel": 1,
# # #             "midi": [176, 22, 0, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 7,
# # #         },
# # #         "8": {
# # #             "channel": 1,
# # #             "midi": [176, 23, 0, 176],
# # #             "actions": ["mixer_pan", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 8,
# # #         },
# # #         "9": {
# # #             "channel": 1,
# # #             "midi": [176, 0, 78, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "10": {
# # #             "channel": 1,
# # #             "midi": [176, 1, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "11": {
# # #             "channel": 1,
# # #             "midi": [176, 2, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "12": {
# # #             "channel": 1,
# # #             "midi": [176, 3, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 4,
# # #         },
# # #         "13": {
# # #             "channel": 1,
# # #             "midi": [176, 4, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 5,
# # #         },
# # #         "14": {
# # #             "channel": 1,
# # #             "midi": [176, 5, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 6,
# # #         },
# # #         "15": {
# # #             "channel": 1,
# # #             "midi": [176, 6, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 7,
# # #         },
# # #         "16": {
# # #             "channel": 1,
# # #             "midi": [176, 7, 0, 176],
# # #             "actions": ["mixer_level", "selected_level"],
# # #             "toggle": 0,
# # #             "track": 8,
# # #         },
# # #     },
# # #     "buttons": {
# # #         "17": {
# # #             "channel": 1,
# # #             "midi": [176, 120, 0, 176],
# # #             "actions": ["down", "down"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "18": {
# # #             "channel": 1,
# # #             "midi": [176, 59, 0, 176],
# # #             "actions": ["up", "up"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "19": {
# # #             "channel": 1,
# # #             "midi": [176, 46, 0, 176],
# # #             "actions": ["change_mode", "change_mode"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "20": {
# # #             "channel": 1,
# # #             "midi": [176, 60, 0, 176],
# # #             "actions": ["shift", "shift"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "21": {
# # #             "channel": 1,
# # #             "midi": [176, 61, 0, 176],
# # #             "actions": ["rand_pattern", "rand_pattern"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "22": {
# # #             "channel": 1,
# # #             "midi": [176, 62, 0, 176],
# # #             "actions": ["rotate_set_windows", "rotate_set_windows"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "23": {
# # #             "channel": 1,
# # #             "midi": [176, 43, 0, 176],
# # #             "actions": ["left", "start"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "24": {
# # #             "channel": 1,
# # #             "midi": [176, 44, 0, 176],
# # #             "actions": ["right", "right"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "25": {
# # #             "channel": 1,
# # #             "midi": [176, 42, 0, 176],
# # #             "actions": ["stop", "stop"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "26": {
# # #             "channel": 1,
# # #             "midi": [176, 41, 0, 176],
# # #             "actions": ["start", "start"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "27": {
# # #             "channel": 1,
# # #             "midi": [176, 45, 0, 176],
# # #             "actions": ["record", "record"],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "29": {
# # #             "channel": 1,
# # #             "midi": [176, 32, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "30": {
# # #             "channel": 1,
# # #             "midi": [176, 33, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "31": {
# # #             "channel": 1,
# # #             "midi": [176, 34, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "32": {
# # #             "channel": 1,
# # #             "midi": [176, 35, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 4,
# # #         },
# # #         "33": {
# # #             "channel": 1,
# # #             "midi": [176, 36, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 5,
# # #         },
# # #         "34": {
# # #             "channel": 1,
# # #             "midi": [176, 37, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 6,
# # #         },
# # #         "35": {
# # #             "channel": 1,
# # #             "midi": [176, 38, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 7,
# # #         },
# # #         "36": {
# # #             "channel": 1,
# # #             "midi": [176, 39, 0, 176],
# # #             "actions": ["mixer_solo", "start"],
# # #             "toggle": 0,
# # #             "track": 8,
# # #         },
# # #         "37": {
# # #             "channel": 1,
# # #             "midi": [176, 48, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "38": {
# # #             "channel": 1,
# # #             "midi": [176, 49, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "39": {
# # #             "channel": 1,
# # #             "midi": [176, 50, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "40": {
# # #             "channel": 1,
# # #             "midi": [176, 51, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 4,
# # #         },
# # #         "41": {
# # #             "channel": 1,
# # #             "midi": [176, 52, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 5,
# # #         },
# # #         "42": {
# # #             "channel": 1,
# # #             "midi": [176, 53, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 6,
# # #         },
# # #         "43": {
# # #             "channel": 1,
# # #             "midi": [176, 54, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 7,
# # #         },
# # #         "44": {
# # #             "channel": 1,
# # #             "midi": [176, 55, 0, 176],
# # #             "actions": ["mixer_mute", "start"],
# # #             "toggle": 0,
# # #             "track": 8,
# # #         },
# # #         "45": {
# # #             "channel": 1,
# # #             "midi": [176, 64, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "46": {
# # #             "channel": 1,
# # #             "midi": [176, 65, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "47": {
# # #             "channel": 1,
# # #             "midi": [176, 66, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "48": {
# # #             "channel": 1,
# # #             "midi": [176, 67, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 4,
# # #         },
# # #         "49": {
# # #             "channel": 1,
# # #             "midi": [176, 68, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 5,
# # #         },
# # #         "50": {
# # #             "channel": 1,
# # #             "midi": [176, 69, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 6,
# # #         },
# # #         "51": {
# # #             "channel": 1,
# # #             "midi": [176, 70, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 7,
# # #         },
# # #         "52": {
# # #             "channel": 1,
# # #             "midi": [176, 71, 0, 176],
# # #             "actions": ["mixer_record", "start"],
# # #             "toggle": 0,
# # #             "track": 8,
# # #         },
# # #     },
# # #     "keyboard": {
# # #         "69": {
# # #             "channel": 1,
# # #             "midi": [176, 33, 0, 176],
# # #             "actions": ["C#", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "70": {
# # #             "channel": 1,
# # #             "midi": [176, 35, 0, 176],
# # #             "actions": ["D#", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "71": {
# # #             "channel": 1,
# # #             "midi": [176, 38, 0, 176],
# # #             "actions": ["F#", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "72": {
# # #             "channel": 1,
# # #             "midi": [176, 48, 0, 176],
# # #             "actions": ["G#", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "73": {
# # #             "channel": 1,
# # #             "midi": [176, 50, 0, 176],
# # #             "actions": ["A#", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "74": {
# # #             "channel": 1,
# # #             "midi": [176, 32, 0, 176],
# # #             "actions": ["C", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "75": {
# # #             "channel": 1,
# # #             "midi": [176, 34, 0, 176],
# # #             "actions": ["D", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "76": {
# # #             "channel": 1,
# # #             "midi": [176, 36, 0, 176],
# # #             "actions": ["E", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "77": {
# # #             "channel": 1,
# # #             "midi": [176, 37, 0, 176],
# # #             "actions": ["F", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "78": {
# # #             "channel": 1,
# # #             "midi": [176, 39, 0, 176],
# # #             "actions": ["G", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "79": {
# # #             "channel": 1,
# # #             "midi": [176, 49, 0, 176],
# # #             "actions": ["A", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "80": {
# # #             "channel": 1,
# # #             "midi": [176, 51, 0, 176],
# # #             "actions": ["B", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "81": {
# # #             "channel": 1,
# # #             "midi": [176, 53, 0, 176],
# # #             "actions": ["C#", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "82": {
# # #             "channel": 1,
# # #             "midi": [176, 55, 0, 176],
# # #             "actions": ["D#", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "83": {
# # #             "channel": 1,
# # #             "midi": [176, 66, 0, 176],
# # #             "actions": ["F#", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "84": {
# # #             "channel": 1,
# # #             "midi": [176, 68, 0, 176],
# # #             "actions": ["G#", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "85": {
# # #             "channel": 1,
# # #             "midi": [176, 71, 0, 176],
# # #             "actions": ["A#", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "86": {
# # #             "channel": 1,
# # #             "midi": [176, 52, 0, 176],
# # #             "actions": ["C", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "87": {
# # #             "channel": 1,
# # #             "midi": [176, 54, 0, 176],
# # #             "actions": ["D", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "88": {
# # #             "channel": 1,
# # #             "midi": [176, 64, 0, 176],
# # #             "actions": ["E", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "89": {
# # #             "channel": 1,
# # #             "midi": [176, 65, 0, 176],
# # #             "actions": ["F", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "90": {
# # #             "channel": 1,
# # #             "midi": [176, 67, 0, 176],
# # #             "actions": ["G", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "91": {
# # #             "channel": 1,
# # #             "midi": [176, 69, 0, 176],
# # #             "actions": ["A", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #     },
# # #     "sequencer": {
# # #         "53": {
# # #             "channel": 1,
# # #             "midi": [176, 48, 0, 176],
# # #             "actions": ["0", "0"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "54": {
# # #             "channel": 1,
# # #             "midi": [176, 49, 0, 176],
# # #             "actions": ["1", "1"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "55": {
# # #             "channel": 1,
# # #             "midi": [176, 50, 0, 176],
# # #             "actions": ["2", "2"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "56": {
# # #             "channel": 1,
# # #             "midi": [176, 51, 0, 176],
# # #             "actions": ["3", "3"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "57": {
# # #             "channel": 1,
# # #             "midi": [176, 52, 0, 176],
# # #             "actions": ["4", "4"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "58": {
# # #             "channel": 1,
# # #             "midi": [176, 53, 0, 176],
# # #             "actions": ["5", "5"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "59": {
# # #             "channel": 1,
# # #             "midi": [176, 54, 0, 176],
# # #             "actions": ["6", "6"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "60": {
# # #             "channel": 1,
# # #             "midi": [176, 55, 0, 176],
# # #             "actions": ["7", "7"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "61": {
# # #             "channel": 1,
# # #             "midi": [176, 64, 0, 176],
# # #             "actions": ["8", "8"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "62": {
# # #             "channel": 1,
# # #             "midi": [176, 65, 0, 176],
# # #             "actions": ["9", "9"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "63": {
# # #             "channel": 1,
# # #             "midi": [176, 66, 0, 176],
# # #             "actions": ["10", "10"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "64": {
# # #             "channel": 1,
# # #             "midi": [176, 67, 0, 176],
# # #             "actions": ["11", "11"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "65": {
# # #             "channel": 1,
# # #             "midi": [176, 68, 0, 176],
# # #             "actions": ["12", "12"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "66": {
# # #             "channel": 1,
# # #             "midi": [176, 69, 0, 176],
# # #             "actions": ["13", "13"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "67": {
# # #             "channel": 1,
# # #             "midi": [176, 70, 0, 176],
# # #             "actions": ["14", "14"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "68": {
# # #             "channel": 1,
# # #             "midi": [176, 71, 0, 176],
# # #             "actions": ["15", "15"],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #     },
# # #     "performance": {
# # #         "115": {
# # #             "channel": 1,
# # #             "midi": [176, 32, 0, 176],
# # #             "actions": ["1", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "116": {
# # #             "channel": 1,
# # #             "midi": [176, 33, 0, 176],
# # #             "actions": ["1", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "117": {
# # #             "channel": 1,
# # #             "midi": [176, 34, 0, 176],
# # #             "actions": ["1", ""],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "118": {
# # #             "channel": 1,
# # #             "midi": [176, 35, 0, 176],
# # #             "actions": ["1", ""],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "119": {
# # #             "channel": 1,
# # #             "midi": [176, 48, 0, 176],
# # #             "actions": ["2", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "120": {
# # #             "channel": 1,
# # #             "midi": [176, 49, 0, 176],
# # #             "actions": ["2", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "121": {
# # #             "channel": 1,
# # #             "midi": [176, 50, 0, 176],
# # #             "actions": ["2", ""],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "122": {
# # #             "channel": 1,
# # #             "midi": [176, 51, 0, 176],
# # #             "actions": ["2", ""],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "123": {
# # #             "channel": 1,
# # #             "midi": [176, 64, 0, 176],
# # #             "actions": ["3", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "124": {
# # #             "channel": 1,
# # #             "midi": [176, 65, 0, 176],
# # #             "actions": ["3", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "125": {
# # #             "channel": 1,
# # #             "midi": [176, 66, 0, 176],
# # #             "actions": ["3", ""],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "126": {
# # #             "channel": 1,
# # #             "midi": [176, 67, 0, 176],
# # #             "actions": ["3", ""],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "127": {
# # #             "channel": 1,
# # #             "midi": [176, 36, 0, 176],
# # #             "actions": ["4", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "128": {
# # #             "channel": 1,
# # #             "midi": [176, 37, 0, 176],
# # #             "actions": ["4", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "129": {
# # #             "channel": 1,
# # #             "midi": [176, 38, 0, 176],
# # #             "actions": ["4", ""],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "130": {
# # #             "channel": 1,
# # #             "midi": [176, 39, 0, 176],
# # #             "actions": ["4", ""],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "131": {
# # #             "channel": 1,
# # #             "midi": [176, 52, 0, 176],
# # #             "actions": ["5", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "132": {
# # #             "channel": 1,
# # #             "midi": [176, 53, 0, 176],
# # #             "actions": ["5", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "133": {
# # #             "channel": 1,
# # #             "midi": [176, 54, 0, 176],
# # #             "actions": ["5", ""],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "134": {
# # #             "channel": 1,
# # #             "midi": [176, 55, 0, 176],
# # #             "actions": ["5", ""],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #         "135": {
# # #             "channel": 1,
# # #             "midi": [176, 68, 0, 176],
# # #             "actions": ["6", ""],
# # #             "toggle": 0,
# # #             "track": 0,
# # #         },
# # #         "136": {
# # #             "channel": 1,
# # #             "midi": [176, 69, 0, 176],
# # #             "actions": ["6", ""],
# # #             "toggle": 0,
# # #             "track": 1,
# # #         },
# # #         "137": {
# # #             "channel": 1,
# # #             "midi": [176, 70, 0, 176],
# # #             "actions": ["6", ""],
# # #             "toggle": 0,
# # #             "track": 2,
# # #         },
# # #         "138": {
# # #             "channel": 1,
# # #             "midi": [176, 71, 0, 176],
# # #             "actions": ["6", ""],
# # #             "toggle": 0,
# # #             "track": 3,
# # #         },
# # #     },
# # # }
